### ISSUE TITLE
divide by zero encountered in log

### ISSUE THREAD

**Issue by AndreasMadsen** [piskvorky/gensim#217]
Sometimes when I use the LDA model, I get this warning:

```
gensim/models/ldamodel.py:602: RuntimeWarning: divide by zero encountered in log
diff = numpy.log(self.expElogbeta)
```

I'm using Python 3.4.1 and the develop branch of gensim.

**Comment by tmylk** [comment]
Closig as report is incomplete.

**Comment by ocsponge** [comment]
hi, AndreasMadsen, I got the same warning, how did u solve the problem?

**Comment by AndreasMadsen** [comment]
I don't think I did.

**Comment by yanshengjia** [comment]
Got the same warning, any idea?

**Comment by menshikh-iv** [comment]
@yanshengjia can you sent model/dataset/code for training, that's needed for reproduce your problem

**Comment by yanshengjia** [comment]
Yeah, I can send you the corpus which I use.

**Comment by menshikh-iv** [comment]
@yanshengjia corpus **and** concrete code, that produce this problem on your corpus. That's really important (because if we can't reproduce this problem, we can't help)

**Comment by yanshengjia** [comment]
I have sent the corpus and the code to your gmail.

**Comment by menshikh-iv** [comment]
@yanshengjia I run this with a debugger (with `np.seterr(all='raise')`), but the problem doesn't happen again (probably need exact `seed` value for reproduce it)

**Comment by yanshengjia** [comment]
@menshikh-iv I think the reason why I met that warning is that I didn't split the document. I split the doc and the warning doesn't show again. So It's ok now. Thx a lot!

**Comment by liz282907** [comment]
i've got the same warning, any idea of solving it?

**Comment by menshikh-iv** [comment]
@liz282907 please ignore it (this is very strange, we need to investigate it properly)
CC: @piskvorky

**Comment by Gladysgong** [comment]
i've got the same warning, any idea of solving it?

**Comment by RohitRaj2017** [comment]
/opt/anaconda3/lib/python3.6/site-packages/gensim/models/ldamodel.py:775: RuntimeWarning: divide by zero encountered in log
  diff = np.log(self.expElogbeta)

This is the exact warning that I am getting

**Comment by xiaokc** [comment]
In  my project, alpha and beta are all defaults, but this problem occurred, I donnot know how to solve it

**Comment by annalina** [comment]
I'm getting the same error:
/venv/lib/python2.7/site-packages/gensim/models/ldamodel.py:1023: RuntimeWarning: divide by zero encountered in log diff = np.log(self.expElogbeta)
 I'm training with different topic sizes, from 10 to 100, and measuring the coherence to decide how many topics retain. Everything went well until 80 topics, where I got this error. It seems to be quite random. I'm not saving the model, it was just a small experiment, so there is no way I can reproduce it.

**Comment by mrvsppr** [comment]
Same situation as @annalina 
Code runs lda for multiple topics, num_topic =[20,60] work fine, num_topics=100, built with same corpus and dictionary, gives:

/usr/local/lib/python3.5/dist-packages/gensim/models/ldamodel.py:775: RuntimeWarning: divide by zero encountered in log
  diff = np.log(self.expElogbeta)
/usr/local/lib/python3.5/dist-packages/gensim/models/ldamodel.py:509: RuntimeWarning: overflow encountered in add
  sstats[:, ids] += np.outer(expElogthetad.T, cts / phinorm)
/usr/local/lib/python3.5/dist-packages/gensim/models/ldamodel.py:519: RuntimeWarning: invalid value encountered in multiply
  sstats *= self.expElogbeta

**Comment by menshikh-iv** [comment]
Can anybody provide 
- minimal code example (with needed data) that reproduce this issue
- python/os/numpy/scipy versions

please @mrvsppr @annalina @xiaokc @HibaJak @RohitRaj2017 @Gladysgong @liz282907

**Comment by itsbrycehere** [comment]
I'm running into this error as well now. 

My function looks like this: 
`import operator
from gensim.models.ldamodel import LdaModel
def very_tuned_LDA(corpus, dictionary, lemma_text):
    top_topics = [(0, 0)]
    while top_topics[0][1] < 0.97:
        lm = LdaModel(corpus=corpus, id2word=dictionary, alpha = "auto")
        coherence_values = {}
        for n, topic in lm.show_topics(num_topics = -1, formatted=False): 
            topic = [word for word, _ in topic]
            cm = CoherenceModel(topics=[topic], texts=lemma_text, 
                                dictionary=dictionary, window_size=10)
            coherence_values[n] = cm.get_coherence()
        top_topics = sorted(coherence_values.items(), key=operator.itemgetter(1), reverse=True)
    return lm, top_topics`

id2word, corpus, and text are all built and work in a basic LDA, LSI and HDP.

**Comment by itsbrycehere** [comment]
I'm having the same problem now. Code looks like this. Corpus, id2word and text all work in basic LDA, HDP, and LSI. 

`import operator`
`from gensim.models.ldamodel import LdaModel`
`def very_tuned_LDA(corpus, dictionary, lemma_text):`
`    ``top_topics = [(0, 0)]`
`    ``while top_topics[0][1] < 0.97:
`        ``lm = LdaModel(corpus=corpus, id2word=dictionary, alpha = "auto")`
`        ``coherence_values = {}`
`        ``for n, topic in lm.show_topics(num_topics = -1, formatted=False): `
`            ``#lda.num_topics fix for bug in show_topics`
`            ``topic = [word for word, _ in topic]`
`            ``cm = CoherenceModel(topics=[topic], texts=lemma_text,` 
`                                                    ``dictionary=dictionary, window_size=10)`
`            ``coherence_values[n] = cm.get_coherence()`
`        ``top_topics = sorted(coherence_values.items(), key=operator.itemgetter(1), reverse=True)`
`    ``return lm, top_topics`

**Comment by menshikh-iv** [comment]
Hi @mrvsppr, thanks, but I can't add it to my dropbox (dropbox say than 2 GB are not enough), how large is it? Can you share it with google-drive (or something else)?

**Comment by Naor-Tedgi** [comment]
`/home/nt/.local/lib/python3.5/site-packages/gensim/models/ldamodel.py:1023: RuntimeWarning: divide by zero encountered in log
diff = np.log(self.expElogbeta)`

`    lda = gensim.models.LdaMulticore(corpus=corpus, num_topics=TOPICS,alpha="symmetric",eta=0.01, iterations=200, id2word=dictionary , workers=11)`

get the same warning now with this parameters 
any news?

**Comment by bylinn** [comment]
get the same warning and any update here? @menshikh-iv thanks!

**Comment by andifunke** [comment]
Try to increase the internal precision by providing dtype=np.float64 as an argument to the LdaModel (default is np.float32). This will prevent the model from truncating very low values to .0, resulting in np.log(.0) = -inf, which then triggers this warning.

However, I'm not sure if some values are supposed to be as low as 1.219e-47, so maybe there is indeed some underlying issue with the implementation, but I'm probably just too paranoid. For my own sanity I evaluated both word depths and couldn't see much difference with respect to perplexity, coherence or convergence metrics.

**Comment by BJWipf** [comment]
I'm also experiencing this problem. I'm using the common_corpus and following the tutorial. Any ideas for resolving? 


>>> from gensim.test.utils import common_corpus
>>> from gensim.models import LdaSeqModel
>>>
>>> ldaseq = LdaSeqModel(corpus=common_corpus, time_slice=[2, 4, 3], num_topics=2, chunksize=1)


C:\Users\Briana\AppData\Local\Continuum\anaconda3\lib\site-packages\gensim\models\ldaseqmodel.py:293: RuntimeWarning: divide by zero encountered in double_scalars
  convergence = np.fabs((bound - old_bound) / old_bound)

**Comment by Yaeyang** [comment]
Still got the same problem when calculating the c_uci coherence. 
RuntimeWarning: divide by zero encountered in scalar divide  m_lr_i = np.log(numerator / denominator)
I have set the printoptin of numpy.
`np.set_printoptions(precision=10)
# np.set_printoptions(threshold=np.inf)`

Did anyone solve the problem?
