### ISSUE TITLE
Word2Vec Cbow: Minor error in sgd update

### ISSUE THREAD

**Issue by ogh** [piskvorky/gensim#242]
Hi,

I just noticed a minor error in word2vec cbow regarding the sgd updates.

It's easiest to demonstrate it with an example:

Say the window I am currently looking at is: `the dog and the cat`
Note that `the` appears twice!

In line [168-171](https://github.com/piskvorky/gensim/blob/8ce3231cbf47024f69e54941bb5c0cceb7d07bd7/gensim/models/word2vec.py#L168-171) the function retrieves the indices corresponding to each of the words, looks them up in the wordvec table and computes their mean.

Say we are using the hierarchical softmax version then line [174-179](https://github.com/piskvorky/gensim/blob/8ce3231cbf47024f69e54941bb5c0cceb7d07bd7/gensim/models/word2vec.py#L174-179) will compute the gradient with respect to the words in the word window.
Since the representation of the word window is created by averaging the word vectors of this window, the gradient for each of the individual words is exactly the same. Therefore, we end up with a single gradient vector instead of a whole array that contains one row per individual word.

Up until here, everything is correct.

The problem is in line [194](https://github.com/piskvorky/gensim/blob/8ce3231cbf47024f69e54941bb5c0cceb7d07bd7/gensim/models/word2vec.py#L194)

    model.syn0[word2_indices] += neu1e

where `word2_indices` is a list of indices.
When you update the rows corresponding to a list of indices, numpy has an odd way of dealing with indices appearing twice (or multiple times). 

Example

    a = np.array([0., 1., 2., 3.])
    a[0] += 2
    a[0] += 3
    array([ 5.,  1.,  2.,  3.])

If I add first `2` and then `3`, I get `array([ 5.,  1.,  2.,  3.])`, just as expected.
If I attempt to perform the same operation, but using fancy indexing:

    a = np.array([0., 1., 2., 3.])
    a[[0,0]] += [2,3]
    array([ 3.,  1.,  2.,  3.])

I end up with `3` instead of `5`. The first update is simply ignored.

So to come back to word2vec. If I have words like `the` occuring twice or more times within one window in the cbow implementation, all updates of the word except the last one will simply be ignored.

The only way to solve this that I can think of right now, is to use a loop instead of the fancy indexing. That would probably kill a lot of speed though.
Glancing over the cython version, it seems that the update is done with a loop there, so the issue should be resolved there.

The implementation works just fine so I think it's not a big problem.
Just thought it's good to be aware of it, at least to me it was a bit baffling at first.

**Comment by tmylk** [comment]
@gojomo should this be added as a PR? or closed?

**Comment by gojomo** [comment]
I believe other changes fixed the python path here. (The highlighted line no longer exists; in its place is an index-by-index update.
