### ISSUE TITLE
poincare model does not work when workers > 1

### ISSUE THREAD

**Issue by koiizukag** [piskvorky/gensim#2515]
The document says `workers` (int, optional) – Number of threads to use for training the model.
https://radimrehurek.com/gensim/models/poincare.html
But there is no implementation for multi-threads in poincare model.
https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/poincare.py#L594

**Comment by mdkabirrana** [comment]
I am getting same issue.

**Comment by ayan-iiitd** [comment]
Using Gensim 4.0.1 from conda-forge, multi-threading is still not there for Poincare!!

**Comment by alaeddingurel** [comment]
I'm using Gensim 4.3.2, are there any updates about implementation?

**Comment by mpenkov** [comment]
Please post a stack trace.

**Comment by d4tum** [comment]
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In[118], line 19
      8 dtype=np.float32
     10 model = PoincareModel(
     11     relationships, 
     12     size=size, 
   (...)
     17     dtype=dtype,
     18     seed=0)
---> 19 model.train(epochs=epochs)

File ~/python3.10/site-packages/gensim/models/poincare.py:629, in PoincareModel.train(self, epochs, batch_size, print_every, check_gradients_every)
    603 """Train Poincare embeddings using loaded data and model parameters.
    604 
    605 Parameters
   (...)
    626 
    627 """
    628 if self.workers > 1:
--> 629     raise NotImplementedError("Multi-threaded version not implemented yet")
    630 # Some divide-by-zero results are handled explicitly
    631 old_settings = np.seterr(divide='ignore', invalid='ignore')

NotImplementedError: Multi-threaded version not implemented yet

**Comment by piskvorky** [comment]
There is zero chance this model will ever be updated, sorry.
