### ISSUE TITLE
The pypi repo still fails to install with python 3

### ISSUE THREAD

**Issue by esafak** [piskvorky/gensim#269]
I refer you to [gensim 0.10.0 pip/easy_install errors (Python 3.3)](http://comments.gmane.org/gmane.comp.ai.gensim/3188), where a user reported the same errors:

      File "/home/emre/.local/lib/python3.4/site-packages/gensim/models/tst.py", line 61
        print best_dist, matched
                      ^
    SyntaxError: Missing parentheses in call to 'print'
    
      File "/home/emre/.local/lib/python3.4/site-packages/gensim/models/test.py", line 13
        print model.syn0
                  ^
    SyntaxError: Missing parentheses in call to 'print'
    
      File "/home/emre/.local/lib/python3.4/site-packages/gensim/models/saul.py", line 71
        print QSim(documents[i])
                 ^
    SyntaxError: invalid syntax

That thread was from July 2014; I thought this problem would have been resolved by now. Is anyone else observing the same behavior with python3 and pip, or is it just me?

**Comment by piskvorky** [comment]
Should be fixed now -- please reopen if you're experiencing the problem. Thanks!
