### ISSUE TITLE
Corpus for DTM model

### ISSUE THREAD

**Issue by hyhan** [piskvorky/gensim#271]
I tried to do some text mining using the Dynamic Topic Models (DTM) in the gensim. But it didn't work with a huge increase in memory demand.

I found that the wrapper may not generate the right output format based on the gensim corpus. More specifically speaking, each line of the generated output is ```unique_word_count index1:count1 index2:count2 ... indexn:counnt```, where each count is a float number, e.g. 1.0, 5.0. However, looks like the binary application can only read the count as integers (```read_corpus``` function in ```dtm/data.c``` in the [source files](https://code.google.com/p/princeton-statistical-learning/downloads/detail?name=dtm_release-0.8.tgz)).

I simply changed line 111 in ```save_corpus``` function in ```corpora/bleicorpus.py```: ```parts = ["%i:%d" % p for p in doc if abs(p[1]) > 1e-7]```. It then works.

**Comment by tmylk** [comment]
Fixed by DTM ipynb tutorial
