### ISSUE TITLE
Tutorial use of corpse2dense incorrect

### ISSUE THREAD

**Issue by cmpdev** [piskvorky/gensim#274]
I don't know what the correct usage would be, but tutorial 1 (https://radimrehurek.com/gensim/tut1.html) has a minor issue when using `matutils.corpus2dense(corpus)` which still needs the num_terms field according to the API docs.

On a side note, what would be the correct value to pass in the context of the tutorial? None, `len(corpus)`, and 0-2 haven't worked so far.

**Comment by piskvorky** [comment]
Thanks for pointing that out, will fix the docs.

Correct value is the number of features in your corpus. So, `len(id2word)` if the corpus is bag-of-words, or `num_topics` if it's LSA/LDA corpus etc.
