### ISSUE TITLE
default label index in doc2vec_inner.train_sentence_dbow

### ISSUE THREAD

**Issue by fbkarsdorp** [piskvorky/gensim#275]
I'm not sure whether this is a bug, or intended behavior, but In line [751](https://github.com/piskvorky/gensim/blob/develop/gensim/models/doc2vec_inner.pyx#L751) a variable `l` is defined to loop over all labels of a sentence. However, in both line [758](https://github.com/piskvorky/gensim/blob/develop/gensim/models/doc2vec_inner.pyx#L758) and line [760](https://github.com/piskvorky/gensim/blob/develop/gensim/models/doc2vec_inner.pyx#L760) where the calls are made to `fast_sentence_dbow_hs` and `fast_sentence_dbow_neg` respectively, the index `j` is used in `lbl_indexes[j]`. Shouldn't this be `l`? It can imagine it should if a sentence contains multiple labels.

**Comment by piskvorky** [comment]
Hmm, seems to be the same bug from here: https://github.com/piskvorky/gensim/pull/231/files#r18437281

Now I see @temerick actually replied there, which I didn't see (github is refusing to send me notifications). Any plans to merge the fix, Tim? There was one more `l` like that, just below.

**Comment by temerick** [comment]
Sure. I'll take care of it.

**Comment by piskvorky** [comment]
Should be fixed in #282 by @temerick . Feel free to close if this fix works for you, @fbkarsdorp .

**Comment by fbkarsdorp** [comment]
Great. Thanks!
