### ISSUE TITLE
Pachinko allocation available?

### ISSUE THREAD

**Issue by TimoStolz** [piskvorky/gensim#286]
Hello piskvorky,

thank's a lot for this great library. We use it at our university to uncover topics in messages of patients that use our expert-guided self-help treatments for mental health issues.

Is it possible to do a Pachinko allocation model with gensim? That would help a lot, because these models may uncover correlations between topics in addition to the word correlations within topics. Wikipedia gives a very [brief introduction](http://en.wikipedia.org/wiki/Pachinko_allocation) (and another [here](http://en.wikipedia.org/wiki/Topic_model)) and points to some literature.

Again, thanks a lot for this truly great tool!

Timo Stolz, University of Berne, Switzerland

**Comment by piskvorky** [comment]
Hello, you're welcome :)

More topic modelling techniques are on the [Feature proposals](https://github.com/piskvorky/gensim/wiki/Ideas-&-Feature-proposals) page, including Pachinko Allocation.

Nobody implemented it in gensim them yet, so no, not available at the moment. Contributions welcome.

**Comment by TimoStolz** [comment]
Thanks a lot. I'm afraid I'm not enough into it.
