### ISSUE TITLE
Allow dictionary.save to take an open file handle.

### ISSUE THREAD

**Issue by macks22** [piskvorky/gensim#291]
It would improve composability if the `save` method of a `Dictionary` instance could take an open file handle instead of a filename. In particular, there are certain frameworks which only pass around file-like objects and do not use filenames, such as `luigi`. This change would increase compatibility from frameworks like these and provide room for other custom file-like objects to be used.

**Comment by piskvorky** [comment]
That would only work when saving into a single file (no `mmap`, no extra numpy/scipy.sparse arrays being saved). Which is always the case with Dictionary, I think, so no problem.

Implementing should be easy -- a few changes around here https://github.com/piskvorky/gensim/blob/develop/gensim/utils.py#L246 = a special code path for when `fname` is a file handle. Let me know if you want to open a pull request, I'm +1 on this feature.
