### ISSUE TITLE
Treatment of eta is different than in Hoffman's LDA paper

### ISSUE THREAD

**Issue by wbogorad** [piskvorky/gensim#297]
Hi,

In models.ldamodel.py I see that eta is never "decayed" because the only place where it used is in get_lambda() function though self.sstats is decayed by multiplying on rhot:
 def get_lambda(self):
        return self.eta + self.sstats

However in Hoffman's Algorithm 2 in the paper (https://www.cs.princeton.edu/~blei/papers/HoffmanBleiBach2010b.pdf)  and in his original implementation it is different, i.e. the eta is decayed as below:
        self._lambda = self._lambda * (1-rhot) + \
            rhot * (self._eta + self._D * sstats / len(docs))

Does not this discrepancy render the implementation incorrect?
Thanks

**Comment by piskvorky** [comment]
Hello, I don't see eta decaying, either in the paper or in the code you pasted.

Eta stays the same throughout. The rhot factor only decides how to "blend" the "old" lambda with the "new" lambda during model updates (linear blend: old gets `1-rhot` weight, new `rhot` weight).

**Comment by wbogorad** [comment]
Radim,

I agree with you that as rhot gets smaller and smaller with time, the new updates affect the model less and less.
However, I'd like to point out that in your implementation you set lambda as the following using  pseudo-code:
self._lambda = self.eta + self.sstats * (1-rhot) * scale + \
rhot *scale* other_sstats

while in Hoffman's implementation
it is 
self._lambda = self._lambda * (1-rhot)*scale + \
rhot * (self._eta + other_sstats *scale)

In the former the prior impacts the lambda always the same regardless of rhot while in the latter impact of the prior (i.e. eta) diminishes with time.

I'd like to say that I am a big fan of your work and your implementation is clean and easy to follow.

**Comment by piskvorky** [comment]
Hmm, maybe. In the model update `self._lambda * (1-rhot) * scale + rhot * (self._eta + other_sstats *scale)`, if you write the old lambda as `eta + sstats`, the scaled `eta`s don't cancel in Algo 2:

`(1-rhot) * (eta + sstats) * scale + rhot * (eta + other_sstats * scale)` = 
`((1-rhot) * eta * scale) + ((1-rhot) * sstats * scale) + (rhot * eta) + (rhot * other_sstats * scale)` =
`(eta * scale - rhot * eta * scale + rhot * eta) + (1-rhot) * sstats * scale + rhot * other_sstats * scale`

vs. gensim's:
`(eta) + (1-rhot) * sstats * scale + rhot * other_sstats * scale`

The two results are identical for `scale=1.0`. Which I think is the default behaviour in gensim.

I don't remember the details anymore (though I'm sure I checked when I first wrote it), so I'd be grateful if you could check the scaling logic @wbogorad .

And we should probably follow the Algo 2 version faithfully anyway for all cases -- can you do a PR?

**Comment by wbogorad** [comment]
I am glad that now we are on the same page. Indeed, by default the scale is 1.0

I think that your scaling logic departs from Hoffman's but I am not sure if it materially impacts correctness.
Specifically, both sstats and other have their own scale factors in gensim:
(eta) + (1-rhot) * sstats * scale + rhot * other_sstats * scale_other
Obviously, when scale and scale_other are 1 there are no issues.

However, if self.numdocs < targetsize scale becomes > 1 therefore the net result is that the old updates weigh more and more with respect to the new updates making system even more conservative toward the changes that Algorithm 2 prescribes.

Your treatment of scale_other is consistent with Algorithm 2 and Hoffman's.

In this analysis I assume that targetsize is an estimate of the maximum number of documents that could ever be seen. (A comment about that would not hurt ;) ).

Yes, I can do a PR but it will not be quick. I am very busy at the moment.

**Comment by piskvorky** [comment]
No problem, I'll leave this open. PR will be appreciated.

**Comment by tmylk** [comment]
Fixed by cross-checking with sklearn implementation based on Hoffmann in https://github.com/piskvorky/gensim/issues/457
