### ISSUE TITLE
LdaMallet breaks with Large number of documents (>400k)

### ISSUE THREAD

**Issue by chiragnagpal** [piskvorky/gensim#299]
I have been trying to use the Mallet wrapper in gensim for topic modelling tweets, however, when the corpus has more than 400k documents, LdaMallet breaks

**Comment by piskvorky** [comment]
How do you know? Can you specify "breaks", ideally with a concrete log + error message?

**Comment by chiragnagpal** [comment]
![screenshot from 2015-03-04 08 09 07](https://cloud.githubusercontent.com/assets/4943802/6477166/08e410aa-c246-11e4-987a-9584cc55250a.png)

I initially thought of it to be a memory issue, so increased the size of /tmp and also tried changing the prefix location to a physical disk. 

That helps, as I am able to train my model, however in the step, wherein gensim tries to extract the topics from the MALLET file, it again shows an error, 'too many values to unpack'

![screenshot from 2015-03-04 09 10 31](https://cloud.githubusercontent.com/assets/4943802/6477871/75190052-c24e-11e4-97eb-a5db44067109.png)

**Comment by cscorley** [comment]
Just to cross post, there is also a thread on this happening on the mailing list: https://groups.google.com/forum/#!topic/gensim/uEZiu9hbMYg

I'll be looking into fixing this problem this weekend!

**Comment by piskvorky** [comment]
Thanks Christopher!

**Comment by cscorley** [comment]
I think I nailed the problem in the mailing list, have a look. It likely comes down to tokens having whitespace in them (e.g., tab, non-breaking space, etc). Either make sure you're decoding the source data and tokenizing it correctly first (e.g., it could be in encoded in something not UTF-8), or don't build bigrams with spaces! :)

However, the fix, on Gensim's end, is to only split on the single space character only, and not any whitespace.

**Comment by cscorley** [comment]
If you don't mind, @chiragnagpal, try using the new `gensim.models.wrappers.LdaMallet` on develop branch. Note that it's been moved to a new submodule. I believe it should solve the problem of reading in the file.

**Comment by chiragnagpal** [comment]
@cscorley  thnx man! ur a lifesaver! I used a better tokeniser and now its working like a charm!

**Comment by cscorley** [comment]
Great! Glad to hear its working for you now :beers:

Going to close this issue.
