### ISSUE TITLE
Problem with replicating the results for most_similar(positive=['woman', 'king'], negative=['man'], topn=1)

### ISSUE THREAD

**Issue by nick-magnini** [piskvorky/gensim#312]
I trained a model with these settings: 

>>> sentences = word2vec.Text8Corpus(corpus_dir + '/text8')
>>> model = word2vec.Word2Vec(sentences, size=200, window=5, workers=8)
>>> model.most_similar(positive=['woman', 'king'], negative=['man'], topn=5)

I get this results:
[(u'viii', 0.549266517162323), (u'henry', 0.521343469619751), (u'vii', 0.5179285407066345), (u'heir', 0.5172719955444336), (u'illegitimate', 0.5079410672187805)]

Is there anyway that I can replicate the "queen" as top first?
I also tried with no workers=8 (single thread)
>>> model = word2vec.Word2Vec(sentences, size=200, window=5

 and the results is:
[(u'wenceslaus', 0.5203313827514648), (u'queen', 0.508660614490509), (u'daughter', 0.504875898361206), (u'henry', 0.49545571208000183), (u'eleonore', 0.4937078356742859)]

Where the problem could be?

**Comment by piskvorky** [comment]
Too little data. Try with a larger corpus (text9).

What the "most similar word" will be is not a logical certainty, it's a function of the training data. 
Indeterminism using multiple worker threads can change the results too, though with enough data, this is not as pronounced.
