### ISSUE TITLE
LdaModel.save does not allow setting `ignore` to a custom value

### ISSUE THREAD

**Issue by mattilyra** [piskvorky/gensim#314]
In `LdaModel.save` the `ignore` list is explicitly passed to the parent method, making it impossible to add anything to that list. I propose that the `ignore` list be handled in the following way instead.

    if 'ignore' in kwargs:
        kwargs['ignore'] = list(set(['state', 'dispatcher']) | set(kwargs['ignore']))
    else:
        kwargs['ignore'] = ['state', 'dispatcher']
    super(LdaModel, self).save(fname, *args, **kwargs)

**Comment by piskvorky** [comment]
That makes sense, thanks! Can you open a pull request?

**Comment by mattilyra** [comment]
how do I add a PR to an existing issue?

**Comment by piskvorky** [comment]
They're not connected; just open a PR, and from the commit, say `closes #314`.
