### ISSUE TITLE
bigrams and trigrams in Phrases

### ISSUE THREAD

**Issue by nick-magnini** [piskvorky/gensim#318]
I tested the bigram generation using your test example and it works. But when we have the whole corpus as one sentence then it will not.

sentences = [
    ['human', 'interface', 'computer'],
    ['survey', 'user', 'computer', 'system', 'response', 'time'],
    ['eps', 'user', 'interface', 'system'],
    ['system', 'human', 'system', 'eps'],
    ['user', 'response', 'time'],
    ['trees'],
    ['graph', 'trees'],
    ['graph', 'minors', 'survey'],
    ['graph', 'minors', 'survey']
]

>>> bigram = Phrases(sentences, min_count=1, threshold=1)
>>> print list(bigram[sentences])

[[u'human', u'interface', u'computer'], [u'survey', u'user', u'computer', u'system', u'response_time'], [u'eps', u'user', u'interface', u'system'], [u'system', u'human', u'system', u'eps'], [u'user', u'response_time'], [u'trees'], [u'graph', u'trees'], [u'graph_minors', u'survey'], [u'graph_minors', u'survey']]

>>> trigram = Phrases(bigram[sentences],min_count=1, threshold=1)
>>> print list(trigram[bigram[sentences]])

[[u'human', u'interface', u'computer'], [u'survey', u'user', u'computer', u'system', u'response_time'], [u'eps', u'user', u'interface', u'system'], [u'system', u'human', u'system', u'eps'], [u'user', u'response_time'], [u'trees'], [u'graph', u'trees'], [u'graph_minors_survey'], [u'graph_minors_survey']]

>>> sent = [u'new', u'york', u'new', u'york', u'new', u'york']
>>> bigram = Phrases(sent,min_count=1,threshold=1)
>> print list(bigram[sent])

[u'new', u'york', u'new', u'york', u'new', u'york']

>>> sent = [[u'new', u'york', u'new', u'york', u'new', u'york']]
>>> bigram = Phrases(sent,min_count=1,threshold=1)
>> print list(bigram[sent])

[[u'new', u'york', u'new', u'york', u'new', u'york']]

Moreover, why in the first test, 'minors', 'survey' will not be detected as a bigram? There should be two bigrams and one trigram: 'graph_minors' and 'minors_survey'.

I also tried training a w2v model based on bi and trigrams on text8 and the "new_york_times" is not in the vocabulary. Although there are many of new_york_times in the text8 corpus.

**Comment by tmylk** [comment]
Hi @nick-magnini this kind of query is best suited for gensim mailing list https://groups.google.com/forum/#!forum/gensim
