### ISSUE TITLE
Word2vec not training

### ISSUE THREAD

**Issue by fccoelho** [piskvorky/gensim#319]
I am trying to use the latest gensim with python 3 but it simply does not start training the nnet after ingesting the sentences:

```
2015-04-09 08:53:38,848 : INFO : PROGRESS: at sentence #40000, processed 11825151 words and 176854 word types
2015-04-09 08:53:42,090 : INFO : collected 200158 word types from a corpus of 14837441 words and 50000 sentences
2015-04-09 08:53:42,163 : INFO : total 17671 word types after removing those with count<50
2015-04-09 08:53:42,163 : INFO : constructing a huffman tree from 17671 words
2015-04-09 08:53:42,699 : INFO : built huffman tree with maximum node depth 18
2015-04-09 08:53:42,714 : INFO : resetting layer weights
2015-04-09 08:53:43,103 : INFO : training model with 8 workers on 17671 vocabulary and 500 features, using 'skipgram'=1 'hierarchical softmax'=1 'subsample'=0 and 'negative sampling'=0
2015-04-09 08:53:43,124 : INFO : reached the end of input; waiting to finish 0 outstanding jobs
2015-04-09 08:53:43,125 : INFO : training on 0 words took 0.0s, 0 words/s
2015-04-09 08:53:43,125 : INFO : saving Word2Vec object under MediaCloud_d2v, separately None
2015-04-09 08:53:43,125 : INFO : not storing attribute syn0norm
2015-04-09 08:53:43,421 : INFO : precomputing L2-norms of word weight vectors
```

 Notice that it does not throw any exceptions so I really don't know what may be happening.

**Comment by piskvorky** [comment]
What type are the input sentences?

**Comment by fccoelho** [comment]
sentences are  lists of strings, for example:
```python
['argentino', 'fase', 'final', 'recuperação', 'lesão', 'muscular', 'ainda', 'espera', 'alta', 'médica', 'voltar', 'gramados']
```

**Comment by fccoelho** [comment]
I have found the problem:

I was passing the sentences to word2vec as a generator, but that apparently is not acceptable.

```python
def train_w2v_model(model_name="MediaCloud_w2v"):
    print("Training model...")
    sentences = sentence_gen(50000)
    model = Word2Vec(sentences, workers=num_workers, \
                     size=num_features, min_count=min_word_count, \
                     window=context, iter=3)
```

if I pass a list of sentences, it works.

```python
def train_w2v_model(model_name="MediaCloud_w2v"):
    print("Training model...")
    sentences = sentence_gen(50000)
    model = Word2Vec(list(sentences), workers=num_workers, \
                     size=num_features, min_count=min_word_count, \
                     window=context, iter=3)
```

But that is a big problem as it limits the list of sentences I can pass to word2vec to what can fit available RAM.

Now it works!

**Comment by piskvorky** [comment]
It doesn't have to be a list (any iterable is fine).

You do need two passes: one for vocabulary building, second for vector training. See the [tutorial here](http://radimrehurek.com/2014/02/word2vec-tutorial/).

**Comment by fccoelho** [comment]
Just complementing the answer for those with the same issue: 
Since when we call Word2Vec it does two passes over the iterator if you pass a generator function, when it tries to go through the generator a second time, but it is already exhausted, that's why the training was not happening. so the best solution is to do the training with a single pass over your data, like shown in the tutorial:

```python
model = gensim.models.Word2Vec() # an empty model, no training
model.build_vocab(some_sentences)  # can be a non-repeatable, 1-pass generator
model.train(other_sentences)  # can be a non-repeatable, 1-pass generator
```
But I still think Word2Vec should raise an TypeError exception when it gets a generator for the sentences.

**Comment by piskvorky** [comment]
That's a good idea. Can you add that check + a unittest for it, in a pull request?

**Comment by gojomo** [comment]
Clarifying prior comments: `Word2Vec` requires **at least** 2 passes - exactly one pass for surveying the vocabulary, then at least one pass (but usually more, and by default `epochs=5` five passes) to train. 

Let's say you hav a corpus sequence in a variable like `corpus_sentences`. You can check if it's suitably re-iterable by ensuring it always prints the same count when running the following 3 repeated lines one after the other:

```python
print(sum(1 for _ in corpus_sentences))
print(sum(1 for _ in corpus_sentences))
print(sum(1 for _ in corpus_sentences))
```

(If that prints one legitimate-looking count first, then zeros, you are likely using some sort of works-only-once iterator, instead a truly re-iterable sequence. If it prints the same legitimate-looking count all three times, then you have a proper **iterable** sequence - and you then just want to be sure each item in the sequence is a list-of-tokens.)
