### ISSUE TITLE
Use of `filter_tokens` and `add_documents` on a Dictionary results in multiple token assignment

### ISSUE THREAD

**Issue by bmabey** [piskvorky/gensim#326]
I'm on the latest version, `0.11.1-1`, and have ran into a bug where adding documents after I have filtered tokens is resulting in multiple words being assigned the same token id. 

```python
In [227]: d = gensim.corpora.Dictionary([['foo','bar','baz'], ['foo','bar','bar','baz']])

In [228]: d.token2id
Out[228]: {u'bar': 0, u'baz': 1, u'foo': 2}

In [229]: d.filter_tokens([0])

In [230]: d.token2id
Out[230]: {u'baz': 1, u'foo': 2}

In [231]: d.add_documents([['foo','bar','baz','bar']])

In [232]: d.token2id
Out[239]: {u'bar': 2, u'baz': 1, u'foo': 2}
```
Note how we now have `bar` and `foo` mapping to `2`! This of course results in incorrect bag of words when we convert a document:

```python
In [240]: d.doc2bow(['foo','foo','bar','baz','baz','baz'])
Out[240]: [(1, 3), (2, 2)]
```

**Comment by cscorley** [comment]
Hm, yep. Good catch; going to look into this today. Thanks for the report!

**Comment by piskvorky** [comment]
Maybe we should call `compactify()` automatically after `filter_tokens()`.

Not sure why I left these two as separate methods, but updating the Dictionary after `filter_tokens` (without compactifying) won't work indeed.

**Comment by cscorley** [comment]
@piskvorky Just created a few tests for this, and that seems to work. The problem seems to stem from assuming there aren't any gaps. (Another option to avoid compactifying a bunch is to not care about gaps and use a infinite number generator, but looks harder to implement).

**Comment by bmabey** [comment]
Thanks for the quick turn-around!
