### ISSUE TITLE
Using both hs and negative sampling in word2vec

### ISSUE THREAD

**Issue by LazyParanoid** [piskvorky/gensim#328]
Hi, 

I recently started using `gensim` to train `word2vec` on my dataset. However, after a while I noticed that I used both `hierarchical softmax` and `negative sampling` in my trainer. In my understanding of Milokov's paper, these two are two parallel approximations to speed up the calculation of softmax, and should not be applied the same time.

Is my understanding correct on this issue here? If it is, should one of the arguments in `word2vec` trainer be overwritten by the other? Or, the result should not make sense and we should avoid using both of them together?

Thanks, I'm really puzzled at this moment.

**Comment by seanaedmiston** [comment]
I actually asked this question on the word2vec forums just recently and got
this answer from Tomas Mikolov:
https://groups.google.com/d/msg/word2vec-toolkit/WUWad9fL0jU/LdbWy1jQjUIJ

Essentially - it is possible to apply both - and in fact for certain (non
optimal) cases the results are better on the analogy task. However when
considering training time - it seems it is rarely beneficial to use both
together.

(Like anything - it seems that results will vary depending on your
particular use case.)

**Comment by piskvorky** [comment]
Thanks Sean. Closing this issue.

@LazyParanoid , in general, such questions are better served on mailing lists (gensim or word2vec). The audience is larger there and its open-ended format fits better.
