### ISSUE TITLE
topic inference should return sorted topic list

### ISSUE THREAD

**Issue by chiragnagpal** [piskvorky/gensim#332]
Hi, so when i infer a topic distribution over a given document, using a trained model,
` eg top =  model[document]` 

it returns a list consisting of tulples, off tuopicids and probabilities,

shouldn't this list be sorted, so that it becomes easy to get the topic with highest probability,
`top[0]` should thus correspond to topic with greatest prob.

**Comment by piskvorky** [comment]
The list already is sorted. It is sorted by topicid.

To sort by probability, you can do e.g. `top = sorted(top, key=lambda (topicid, prob): prob, reverse=True)`.
