### ISSUE TITLE
an issue with label in LabeledSentence for doc2vec

### ISSUE THREAD

**Issue by zygmuntz** [piskvorky/gensim#337]
In doc2vec, if you have one label per sequence, you provide it as a tuple or a list:

	ls = LabeledSentence(words, (label,))    # or
	ls = LabeledSentence(words, [label]) 

The problem: gensim doesn't complain when that's not the case:

	ls = LabeledSentence(words, label)		# wrong, no error message

After training, `model[label]` doesn't work - KeyError - and one is left scratching his head "why?".

Possible solution: either accept a single label "as is", without wrapping it in a sequence, or throw an exception to let the user something's wrong.

**Comment by piskvorky** [comment]
I assume your labels are strings?

Or how do you tell apart the two possibilities: "single label that is a sequence" (=interpret string as a single text) vs. "sequence represents multiple labels" (interpret string as an iterable of characters)?

**Comment by zygmuntz** [comment]
Yeah, this crossed my mind. I think sequences would be best made "explicit" (lists etc.), meaning a string implies a single label.

**Comment by piskvorky** [comment]
I have bad experience with type overloading -- how about we fail explicitly instead?

As in, we detect `labels=string`, we raise an exception, telling the user to use a list.

Can you open a PR @zygmuntz ?

**Comment by cscorley** [comment]
I agree, it's better off as explicit.

One alternative is to introduce both ideas as keyword arguments:

- `labels` which requires an iterable,
- `label` which uses whatever object is given directly, wrapped in a list.

**Comment by zygmuntz** [comment]
I'll see what I can do.

**Comment by zygmuntz** [comment]
How about dis:

https://github.com/piskvorky/gensim/pull/338
