### ISSUE TITLE
TypeError when str used as Phrases delimiter in Python 3

### ISSUE THREAD

**Issue by davechallis** [piskvorky/gensim#342]
Under python 3.4, using a `str` instead of `bytes` as a delimiter results in an error:

    >>> gensim.models.phrases.Phrases([['foo', 'bar']], delimiter='_')

    ...
    File "/virtualenvs/p3default/lib/python3.4/site-packages/gensim/models/phrases.py", line 121, in __init__
    self.add_vocab(sentences)
    File "/virtualenvs/p3default/lib/python3.4/site-packages/gensim/models/phrases.py", line 172, in add_vocab
    min_reduce, vocab = self.learn_vocab(sentences, self.max_vocab_size, self.delimiter)
    File "/virtualenvs/p3default/lib/python3.4/site-packages/gensim/models/phrases.py", line 146, in learn_vocab
        vocab[delimiter.join(bigram)] += 1
    TypeError: sequence item 0: expected str instance, bytes found

Instead making the delimiter `bytes` works fine:

    >>> gensim.models.phrases.Phrases([['foo', 'bar']], delimiter=b'_')

**Comment by piskvorky** [comment]
That's true -- but why do you pass in a string then?

The default is a byte string, which is correct:
https://github.com/piskvorky/gensim/blob/develop/gensim/models/phrases.py#L80

Or maybe I misunderstood that problem.

**Comment by davechallis** [comment]
Ah, I guess it just wasn't clear from the documentation that a byte string was needed, i.e. http://radimrehurek.com/gensim/models/phrases.html#gensim.models.phrases.Phrases shows "delimiter='_"" as default argument, rather than "delimiter=b'_'", so copying and pasting that (and changing the delimiter to something else) didn't work as expected under python 3 (but works under python 2 of course).

In my case, the error came up because I wanted to use a non-ascii char '§' as delimiter (since I knew it was a character not present in my corpus).

**Comment by piskvorky** [comment]
Ah, good point. Sphinx (the Python documentation engine) removes the `b' '` qualifier when rendering, leaving only `' '`.

Can you update the `__init__` docs Dave, to explicit mention this? Cheers.

**Comment by davechallis** [comment]
No problem, I'll update the docs when I get a chance :)
