### ISSUE TITLE
FAST_VERSION is -1

### ISSUE THREAD

**Issue by lixiangnlp** [piskvorky/gensim#351]
I install numpy with openblas. and the config is 
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/opt/OpenBLAS/lib']
    language = f77
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/opt/OpenBLAS/lib']
    language = f77
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/opt/OpenBLAS/lib']
    language = f77
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/opt/OpenBLAS/lib']
    language = f77
blas_mkl_info:
  NOT AVAILABLE
Numpy version: 1.9.2

But I install gensim with the github source. I get the result of FAST_VERSION is -1. And I have installed Cython 0.22

When I use doc2vec, a warning appears 

UserWarning: C extension compilation failed, training will be slow. Install a C compiler and reinstall gensim for fast training.

The OS is UBUNTU 14.04. How to activate the fast mode of gensim?

**Comment by gojomo** [comment]
The warning indicates the C-extensions aren't available at runtime. 

I don't think you need cython, unless you're editing the .PYX files and need to regenerate the .C. (Gensim already includes the needed .C.) But, you do need other dev tools, including a C-compiler. 

Things worth trying in no particular order if you still have this problem:

* ensure scipy installed properly (technically it's the source of the fast blas routines)
* ensure ubuntu package 'python-dev' is installed (should bring in other needed C-dev headers/tools)
* reinstall gensim or from within gensim directory try `python setup.py build_ext` and/or `python setup.py install` – output may hint what's failed
* try starting from a 'conda' install (perhaps just 'miniconda'): it seems to do a good job of installing nearly-optimal, independent environments and 'conda install PKG' works for most relevant packages (and latest conda, which includes pip>=7, seems to have intelligent awareness of pip-installed packages as well, including installs from github source like `pip install -e git+ssh://git@github.com/USER/PROJECT#egg=BRANCH`.

**Comment by mattilyra** [comment]
This may also be related to the version of `scipy` you're using. The `word2vev_inner.c` references a deprecated module `scipy.linalg.blas.fblas` in `scipy`. There is another issue already open for that `https://github.com/piskvorky/gensim/issues/382`. There's a temporary solution you can do to your local install detailed on Google groups (https://groups.google.com/forum/#!topic/gensim/isBqIhrw9mk) - you need to change the `fblas` import in `word2vec_inner.pyx` and recompile the `.c` extension.

I started creating a fix for issue #382 yesterday but ran into problems trying to install old versions of `scipy` to test the solution.

**Comment by DirkBrand** [comment]
I have had the same issues on my Ubuntu machine.  I have installed numpy and scipy with openblas and confirmed that they were running fast optimized.  I then install Gensim and tested it with Word2Vec, but I still get the message: "C extension not loaded for Word2Vec, training will be slow, etc.".  I have the latest gcc installed on my machine, so I don't get the issue?  I would really like to use the faster training on Word2Vec, since I have to train on 6 million documents!! It takes forever....

**Comment by gojomo** [comment]
@DirkBrand – is your version of scipy 0.16 or higher? If so it's the issue @mattilyra mentions. The easiest workaround until the fixed gensim is released is probably to uninstall scipy and re-install forcing version 0.15.1 to be used.

**Comment by DirkBrand** [comment]
I rolled back to version 0.15 of scipy and reinstalled gensim, and I can confirm that it is much faster.  I went from 1.5k words/second to 80k words/second.  It meant I could actually use it for what I intended without signing away my life!

Thanks

**Comment by piskvorky** [comment]
Gensim 0.12.2 has been released -- work arounds no longer necessary.

**Comment by negacy** [comment]
Thanks @piskvorky . That was easy and helpful.
