### ISSUE TITLE
Last word can be mistakenly ignored in phrase detection

### ISSUE THREAD

**Issue by ikuyamada** [piskvorky/gensim#352]
In the current implementation of phrases.py, the last word in a sentence is ignored if the word is not in the vocabulary.

The last word is included if it exists in the vocabulary:
```
In [75]: bigram_model[[u'she', u'likes', u'python']]
Out[75]: [u'she', u'likes', u'python']
```

But it is excluded if the word is out-of-vocabulary.
```
In [76]: bigram_model[[u'she', u'likes', u'gensim']]
Out[76]: [u'she', u'likes']
```

**Comment by piskvorky** [comment]
Thanks Ikuya!

Just cleaning up old tickets :)
