### ISSUE TITLE
scipy probably not needed in [build-system.requires] table

### ISSUE THREAD

**Issue by filip-komarzyniec** [piskvorky/gensim#3536]
#### Problem description

I believe that specifying `scipy` as a build-only dependency is unnecessary. 

Pip builds the library in isolated environment (by default) where it first downloads (and alternatively builds) build-only dependencies. This behaviour creates additional problems for architectures for which there are not many _.whl_ distributions, like e.g. **ppc64le**.

#### Steps/code/corpus to reproduce

1) create an environment where there is already an older `scipy` library version installed

2)
```sh
cd gensim/
pip install . 
```

3) As there is no `gensim` _.whl_ distribution for **ppc64le**, pip will try building `gensim` in a new isolated environment with build-only dependencies. 
As there is no `scipy` _.whl_ distribution for ppc64le either, pip will try building that as well. 
Despite the fact that `scipy` is already installed in desired version within the target environment. 
Not only there will be a `scipy` version mismatch (pip will be building the latest version in the isolated environment) but it will also:
    * significantly prolong the install phase, as `scipy` takes relatively long to build from source,  
    * create additional dependencies mess, as `scipy` build requires multiple other dependencies and system-level libraries

#### Desired resolution

I've tested locally installing gensim with modified `pyproject.toml` file (deleted `scipy`) and it works as expected. 
Is there any other logic that does not allow deleting `scipy` as a build-only dependency?

#### Versions

`gensim>4.3.*`

**Comment by mpenkov** [comment]
Are you interested in making a PR @filip-komarzyniec ?

**Comment by filip-komarzyniec** [comment]
Sure, I'll be happy to, thanks! 
I'll issue it shortly
