### ISSUE TITLE
Not able to install either by pip install or downloading source code

### ISSUE THREAD

**Issue by salmanbukhari1** [piskvorky/gensim#3537]
Not able to install either by pip install or downloading source code and running the setup.py I am running a docker container

#### Problem description

What are you trying to achieve? What is the expected result? What are you seeing instead?

#### Steps/code/corpus to reproduce

Include full tracebacks, logs and datasets if necessary. Please keep the examples minimal ("minimal reproducible example").

If your problem is with a specific Gensim model (word2vec, lsimodel, doc2vec, fasttext, ldamodel etc), include the following:

```python
print(my_model.lifecycle_events)
```

#### Versions

Please provide the output of:

```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import struct; print("Bits", 8 * struct.calcsize("P"))
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import gensim; print("gensim", gensim.__version__)
from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
```

**Comment by mpenkov** [comment]
Please provide a full description of your problem.  See the text in the issue body for more. Without details, we cannot help you.

**Comment by salmanbukhari1** [comment]
Sure, @mpenkov please find below the out to the print statements above:

Linux-5.10.76-linuxkit-x86_64-with-glibc2.36
Python 3.9.19 (main, May 14 2024, 09:00:30) 
[GCC 12.2.0]
Bits 64
NumPy 1.26.4
SciPy 1.13.1

running docker container on mac os version 11.6 processor 2 GHz Quad-Core Intel Core i5 and   Processor Name: QuadCore Intel Core i5

my docker file contents are below. I have tried installing with pip install gensim and also downloading the source to and build it to no avail. 

I have been banging my head on this since yesterday and urgently need to complete a task. Any help would be hugely appreciated.

FROM ubuntu:latest
RUN apt update
RUN apt install python3 python3-pip -y
# FROM python:3.9 

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    python3-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Upgrade pip
RUN pip install --upgrade pip --break-system-packages

# Install cython
RUN pip install Cython --break-system-packages

# set the working directory
WORKDIR /app
# Or any preferred Python version.

COPY requirements.txt /app

# install dependencies
RUN pip install --no-cache-dir -r requirements.txt --break-system-packages

# copy the scripts to the folder
COPY . /app

# RUN python gensim/setup.py install
# RUN pip install --upgrade pip setuptools wheel

# RUN apt-get update
# RUN apt-get install gcc

# RUN pip install gensim
RUN pip uninstall gensim --break-system-packages

RUN cd gensim && python setup.py build_ext --inplace

CMD ["python", "./main.py"] 
# Or enter the name of your unique directory and parameter set.

**Comment by mpenkov** [comment]
What is the actual error you are encountering?

**Comment by mathbruyen** [comment]
Cannot say for sure about install from source, but install from pip breaks when scipy `1.13.1` is installed (as reporter mentions) because in the latest available release https://github.com/piskvorky/gensim/commit/ad68ee3f105fc37cf8db333bfb837fe889ff74ac is not included.

Can you make a release of gensim including this commit for pip users to get a version compatible with latest scipy? Do you want me to open a more specific issue?

**Comment by mpenkov** [comment]
Yes, we will be making a new release soon.

Closing as duplicate.
