### ISSUE TITLE
Central word and context

### ISSUE THREAD

**Issue by 1641004802** [piskvorky/gensim#3545]
Excuse me，if I want the window to see the whole document and set it large enough，would gensim choose every word to be the central word and other words to be context？

**Comment by 1641004802** [comment]
And by the way，when Negative sampling，do every word have the same probability to be negative sample or according to the frequency of words appearing in documents.
The source code is quite difficult to read(.pyx), is there any document to explain the details of how the gensim work？

**Comment by gojomo** [comment]
See the documentation for the parameters `window` & `shrink_window` for ways you could arrange for a much-larger (including full-length-of-text) window where all words have equal weight.

The source code is the best reference for fine details of the implementation, with some additional discussion collected in docs & other forums you can find by searching. But, Gensim generally matches the original `word2vec.c` release (& aassociated cademic papers) in how it implements negative-sampling  – with the added `ns_exponent` parameter for extra control for how frequency affects negative-sampling, per the paper linked in the docs for that parameter.

Please ask general usage or comprehension questions at the project discussion list (https://groups.google.com/forum/#!forum/gensim) or StackOverflow or general AI assistants; this issue tracker is for bugs & feature requests.

**Comment by gojomo** [comment]
See the documentation for the parameters `window` & `shrink_window` for ways you could arrange for a much-larger (including full-length-of-text) window where all words have equal weight.

The source code is the best reference for fine details of the implementation, with some additional discussion collected in docs & other forums you can find by searching. But, Gensim generally matches the original `word2vec.c` release (& aassociated cademic papers) in how it implements negative-sampling  – with the added `ns_exponent` parameter for extra control for how frequency affects negative-sampling, per the paper linked in the docs for that parameter.

Please ask general usage or comprehension questions at the project discussion list (https://groups.google.com/forum/#!forum/gensim) or StackOverflow or general AI assistants; this issue tracker is for bugs & feature requests.
