### ISSUE TITLE
Support custom pickle version in utils.SaveLoad

### ISSUE THREAD

**Issue by ccwang002** [piskvorky/gensim#359]
I was trying to load a word2vec model saved in Python 3.4 at Python 2.7 environment. Currently it fails to load due to the unrecognized pickle protocol version 4.  

After digging it down, the `Word2Vec.save()` is defined by `utils.SaveLoad` and it always calls the `utils.pickle` with default argument, which pass the protocol version `-1` implying the highest protocol available.

```python
# utils.py
def pickle(obj, fname, protocol=-1):
     """Pickle object `obj` to file `fname`."""
     with smart_open(fname, 'wb') as fout: # 'b' for binary, needed on Windows
         _pickle.dump(obj, fout, protocol=protocol)

class SaveLoad(object):
    def save(self, fname, separately=None, sep_limit=10 * 1024**2, ignore=frozenset()):
        # ...
        pickle(self, fname)
```

To make saved models work on both Python 2.x and 3.x, the pickle protocol version should be set at 2, the highest version Python 2.x. If user can supply their desired protocol version, it would be easier to switch between Python versions.

Naively, I came up with the following api change:

```python
# utils.py
class SaveLoad(object):
    def save(..., pickle_protocol=-1):
         pickle(self, fname, pickle_protocol)  # same for all places calling pickle
```

Rests of the model implementation (subclass of `SaveLoad`) remains unchanged. Take word2vec as example,

```python
# models/word2vec.py
class Word2Vec(utils.SaveLoad):
     # ...
     def save(self, *args, **kwargs):
         kwargs['ignore'] = kwargs.get('ignore', ['syn0norm']) # don't bother storing the cached normalized vectors
         super(Word2Vec, self).save(*args, **kwargs)
     save.__doc__ = utils.SaveLoad.save.__doc__
```

Whether passing `word2vec.save(..., pickle_protocol=2)` or not doesn't break existed code.

Hope this ease the transition between Python 2 and 3. I could file a pull request if this is feasible.

### EDIT: Current solution

In Python 3.4, run the following code before saving will help convert the existed models

```python
import gensim
import pickle as _pickle

def pickle_py2k_compat(obj, fname, protocol=2):  # change the version number you like
    """Pickle object `obj` to file `fname`."""
    print('Saving %s' % fname)
    with gensim.utils.smart_open(fname, 'wb') as fout: # 'b' for binary, needed on Windows
        _pickle.dump(obj, fout, protocol=protocol)

gensim.utils.pickle = pickle_py2k_compat
```

**Comment by piskvorky** [comment]
Makes sense, thanks for reporting @ccwang002 !

It's probably enough to change the protocol default from `-1` to `2`. There are no issues with pickle performance / memory, so whatever `3` or `4` bring cannot be critical for gensim.

What do you think? Can you craft a PR?

**Comment by ccwang002** [comment]
Some comparison of my custom wiki model using different pickle version. Newer pickle version creates smaller model file, though they take roughly same time to load on my machine. 

```bash
# pickle ver 4
144M    twwiki_400/model
1.3G    twwiki_400/model.syn0.npy
1.3G    twwiki_400/model.syn1.npy

# pickle ver 2
261M    twwiki_py2k_400/model
1.3G    twwiki_py2k_400/model.syn0.npy
1.3G    twwiki_py2k_400/model.syn1.npy
```


Like you said, a normal user should not be able to notice the change. So I guess changing the default pickle version to `2` should work for most people. 

However I hope user can specify their pickle version manually by `model.save(..., pickle_protocol)`. It should only require the change of their base class `utils.SaveLoad`. I haven't thought thoroughly about the API change, not sure if it breaks anything.

I can make a PR in the next few days :)

**Comment by piskvorky** [comment]
Alright, by options are fine by me (change default in `pickle` / allow override in `save`), so whatever works for you.

Looking forward to the PR :)
