### ISSUE TITLE
utils.is_corpus() removes the first item from a generator in Python3

### ISSUE THREAD

**Issue by S-Eugene** [piskvorky/gensim#366]
A minor bug:
utils.is_corpus() removes the first item from a generator on Python 3 because the 'next' attribute was renamed to `__next__`

**Comment by piskvorky** [comment]
But that function doesn't use any `next` attribute. It uses a next `function`.

Can you post exactly what you mean, an example?

**Comment by S-Eugene** [comment]
I came across the issue when I applied tfidf model to a corpus streamed from a generator, eg:

```python
...
corp_bow = (D.doc2bow(sentence) for sentence in doc)
corp_tfidf = tfidf_model[corp_bow]
...
```
It turns out that ```TfidfModel.__getitem__``` checks if the input is a corpus and utils.is_corpus, lines 534 through 541 preserves the first element of the iterator object if it has ```next``` attribute, however in Python 3 it is ```__next__```.
```
        if hasattr(obj, 'next'):
            # the input is an iterator object, meaning once we call next()
            # that element could be gone forever. we must be careful to put
            # whatever we retrieve back again
            doc1 = next(obj)
            obj = itertools.chain([doc1], obj)
        else:
            doc1 = next(iter(obj)) # empty corpus is resolved to False here
```
A fix could be as simple as ` if hasattr(obj, 'next') or  hasattr(obj, '__next__') :` on line 534

**Comment by piskvorky** [comment]
Ah, I see what you mean! Yes, that looks like a bug, and a good fix proposal. Can you open a PR?

**Comment by S-Eugene** [comment]
Done.

**Comment by piskvorky** [comment]
Merged. Many thanks Eugene!
