### ISSUE TITLE
Is there any way to update word2vec model ?

### ISSUE THREAD

**Issue by saj1919** [piskvorky/gensim#368]
Hi, It is not an issue but query .

We want to make word2vec model generation incremental. Currently, it takes ~10 hrs to build a model. Everyday new data comes and we don't want to build new model from scratch ... instead want to update it with new data.

Is it possible in gensim ??

**Comment by piskvorky** [comment]
Yes. You can use the `train` method to continue training.

This limits vocabulary to what you initially passed to `build_vocab` though. If your vocabulary is static (known beforehand), this is not a problem. If you need to be adding new words dynamically though, check out @rutum's pull request [here](https://github.com/piskvorky/gensim/pull/365).

**Comment by saj1919** [comment]
That was quick ... thanks
