### ISSUE TITLE
LdaMulticore does not spawn multiple python processes 

### ISSUE THREAD

**Issue by rvesco** [piskvorky/gensim#371]
I'm using the LDAmulticore function on windows. 

If I use an MM based corpus for the LDAmulticore function, it spawns multiple python processes and runs as expected.

However, if I use an iterator, say for example the one in the gensim tutorial, https://radimrehurek.com/gensim/tut1.html, it never spawns multiple python processes. 

Could it be that my iterator is too slow? Or is there something else at play? How do I write an iterator that will allow ldamulticore to function properly without having to save and load my data to an indexedcorpus format like MM?

**Comment by rvesco** [comment]
So I added a len method to my corpus class and pre-calculated the length of the corpus and now it works as expected. Might be worth adding this note to the tutorial though ... apologies if it's already there and I missed it.

**Comment by ziky90** [comment]
Hi,

I'm sorry for late reply. I have forgotten about this issue and I have rediscovered it now. I'm not sure if this bug is still actual.

I am currently trying to replicate this, but without any success (it seems that everything works as expected). For both corpus with implicit `__len__` method and without it.

**Comment by rvesco** [comment]
Great to hear that. Perhaps it was idiosyncratic to my setup, but in my logs there was a complaint about no len method and the python processes would not spawn. Adding an explicit len method fixed it. In any case, thanks for looking into it!
