### ISSUE TITLE
word2vec_inner compile fail due to import scipy.linalg.blas with scipy 0.17

### ISSUE THREAD

**Issue by ylhsieh** [piskvorky/gensim#382]
I notice that when compiling `word2vec_inner.pyx` it fails at `from scipy.linalg.blas import fblas`. Looking at scipy's [documents](http://docs.scipy.org/doc/scipy/reference/release.0.12.0.html#fblas-and-cblas) I see that this is deprecated since scipy 0.12. Recently I updated my scipy and maybe that caused this error. I changed it to `import scipy.linalg.blas as fblas` to get it to work without modifying other codes. Did anyone encounter this problem?

**Comment by gojomo** [comment]
My working environments are at scipy 0.15.1, and I hadn't noticed any such warning (or failing error), either via the automated install or my manual invocations of cython-compilation. 

How are you compiling that file?

**Comment by ylhsieh** [comment]
Hi, I put `word2vec.py` and `word2vec_inner.pyx` in the same folder, and use the following (modified some imports to make it easier to copy and test):
```python
logger.info("Building word2vec_inner")
import pyximport, os
from numpy import get_include
models_dir = os.getcwd()
pyximport.install(setup_args={"include_dirs": [models_dir, get_include()]})
from word2vec_inner import train_sentence_sg, train_sentence_cbow, FAST_VERSION
logger.info("Built and imported word2vec_inner")
```

It results in 
`ImportError: Building module word2vec_inner failed: ['ImportError: cannot import name fblas\n']`
Perhaps the reason roots from the 0.17 version of scipy? That they officially took out the `fblas`. If I have the time, I would try to downgrade scipy to 0.15 and try again. Thanks.

**Comment by ylhsieh** [comment]
I am deeply sorry to clicked the wrong button! Reopening this.

**Comment by piskvorky** [comment]
Yes, I've seen that deprecation, but forgot to investigate.

@ylhsieh can you investigate? If the fix is as simple as deleting `f` from `fblas`, then let's do it :)

**Comment by ylhsieh** [comment]
Will do. But I suggest to add some version checking in the .pyx files instead of changing it altogether, as some might still be using scipy older than 0.12. For me, changing from `from scipy.linalg.blas import fblas` to `import scipy.linalg.blas as fblas` works, and the rest of the .pyx file can remain the same. This method works for both `word2vec_inner.pyx` and `doc2vec_inner.pyx`.

**Comment by piskvorky** [comment]
Yes, can you check on scipy 0.10.1 please?

That's the latest we have to support (=version in old Debian stable); we can drop the older version. Right now, gensim says it supports any scipy >= 0.7, but I don't think that's necessary, 0.10.1 will do.

**Comment by piskvorky** [comment]
Alternatively, we could hack the Travis (`.travis.yml`) to test with the oldest version supported + the newest version in pip, to automate this.

**Comment by ylhsieh** [comment]
Confirmed using scipy 0.10.1 and 0.15.1, the command `from scipy.linalg.blas import fblas` passed. I did not install 0.16, and my scipy 0.17.1 was pulled from [scipy github] (http://github.com/scipy/scipy.git). So I guess we can close this issue and leave it as a future reference until they make official release of scipy 0.17. Or, should we preemptively add version detection now?

**Comment by piskvorky** [comment]
Yes, `fblas` works with older scipys.

The question is, does `from scipy.linalg.blas import blas` work too?

Is it safe to just always import `scipy.linalg.blas` in scipy >= 0.10.1? Or do we have to try / catch `ImportError` on `fblas`... or dynamically check `scipy.version` to see whether to import `blas` or `fblas`.

**Comment by ylhsieh** [comment]
Just tested in scipy 0.15.1, `from scipy.linalg.blas import blas` does not work.

**Comment by piskvorky** [comment]
Ah, I see. Thanks for checking @ylhsieh !

Can you add the `ImportError` try-catch workaround, in a pull request?

That is, if `import scipy.linalg.blas as fblas` fails, fall back to the current version of `from scipy.linalg.blas import fblas`. And check that it works :) Cheers!

**Comment by ylhsieh** [comment]
I would like to learn how to do that (pull request), but I am a noob to git and not familiar with the PR thingy... Perhaps it would be safer for others to try that? I am afraid I might do some silly stuff (like closing this issue that happened in this thread :weary: )

**Comment by piskvorky** [comment]
GitHub have a [tutorial on pull requests](https://help.github.com/articles/using-pull-requests/).

It's not that complicated and maybe good practice and skill to have :)

And don't worry about "doing silly stuff" -- you don't have write permissions into the "real gensim", so there's no damage you can do. Experiment away!

**Comment by xarg** [comment]
I tried aliasing `from scipy.linalg.blas import blas as fblas` (did the Cython stuff and recompiled) but the import still doesn't work:

```
from gensim.models.word2vec_inner import train_sentence_sg, train_sentence_cbow, FAST_VERSION
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
```

I don't have enough experience with Cython to know why it's not working. 

The workaround that works for me is to downgrade `scipy==0.15.1`

**Comment by piskvorky** [comment]
I've fixed scipy version at 0.15.1 for the Travis tests for now (the automated Travis tests started failing, because of the same issue -- fblas removed).

**Comment by ylhsieh** [comment]
Finally finished creating a PR. I hope I did it right to try to fix this issue.
My first PR! (hooray ??)

**Comment by piskvorky** [comment]
Lemme check :)

**Comment by piskvorky** [comment]
Fixed in #415

**Comment by joelthelion** [comment]
You might want to make a new release even if solely for that issue, since currently "pip install gensim" results in a broken installation and is not very welcoming for newcomers.

**Comment by piskvorky** [comment]
Yeah, will release later today.

**Comment by joelthelion** [comment]
Cool, thanks!
