### ISSUE TITLE
the summarization example doesn't pass

### ISSUE THREAD

**Issue by Fil** [piskvorky/gensim#387]
In PR #324 "Jerry…" has only 6 sentences, and the summarizer rejects it because `INPUT_MIN_LENGTH=10`.

I understand I can do `summarization.summarizer.INPUT_MIN_LENGTH=0`, but I don't like the idea of breaking if one document is too short (a warning might be good enough).

**Comment by piskvorky** [comment]
@fedelopez77 @fbarrios can you have a look?

**Comment by fbarrios** [comment]
@Fil At the moment we are forcing the input text to be longer than 10 sentences because the summary might not make sense otherwise. 
We haven't really considered the option of just raising a warning, I agree now that it's a better alternative. I'll do the changes and make a PR with the fix.

**Comment by tmylk** [comment]
Fixed in https://github.com/piskvorky/gensim/pull/390
