### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by nick-magnini** [piskvorky/gensim#391]
I load the model to the memory. When I query this: 

model.most_similar(positive=['woman', 'king'], negative=['man'], topn=1)

This is the result:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gensim/models/word2vec.py", line 670, in most_similar
    result = [(self.index2word[sim], float(dists[sim])) for sim in best if sim not in all_words]
IndexError: list index out of range

I have vectors for all word. When I check model['woman'] or model['king'], I get the vectors associated with the words. Where is the problem?

**Comment by gojomo** [comment]
Just to be sure there are vectors for all words – and that something like truncation or corruption hasn't happened – do you also get a vector for model['man']?

**Comment by nick-magnini** [comment]
The problem was resolved. I has some strange words I had to delete them. So my number of vocabulary (the first line) was not matching the number of lines. Maybe it is good if the first line of the model is calculated based on the number of vectors if it doesn't match the first line of the model. Just a suggestion.

I had to manually change the first line in order to be able to load the model.

**Comment by gojomo** [comment]
Was the file with the incorrect word-count generated in gensim or word2vec.c? (Is it possible the count was correct at the time written, but the file somehow truncated?)

**Comment by nick-magnini** [comment]
The file was originally was produced by word2vec.c but I had to delete some lines that was not readable in gensim. Deleting those files change the number of vocabulary so I needed to manually change the first line of the file in order to make it work after getting index error.
