### ISSUE TITLE
ValueError: string size must be a multiple of element size for "demo-phrases.sh" trained vector-phrases.bin model file in C

### ISSUE THREAD

**Issue by tpsatish95** [piskvorky/gensim#394]
Hi,

This line,
result.syn0[line_no] = fromstring(fin.read(binary_len), dtype=REAL)
in word2vec.py is giving,
ValueError: string size must be a multiple of element size

The above error occurs only when the word "Nazira" is being handled (the same model file works fine with the distance.c implementation though).

any fix?

**Comment by piskvorky** [comment]
Is "Nazira" perhaps the last word in the file?

`binary_len` is defined as a multiple of the size of `REAL`, so that error doesn't make sense to me.

Must be something connected to skipping whitespace, I think.

Perhaps the C format changed recently? When did you create this binary model, what version of C word2vec?

**Comment by tpsatish95** [comment]
No "Nazira" is somewhere in the middle.
I am using a old C format, I created this binary model about 6 months ago and have been working only in C, but now when i tried in python, i got this error.
It must be a spacing problem, I checked the vector it was 265D but all my other vectors are 300D.
Okay, u want me check with the new C format?

**Comment by piskvorky** [comment]
All word2vec vectors must be the same length, so that's probably some file corruption.

There is no word2vec format that has a variable per-word vector length.

It's really strange that you say this file works with the C tool... are you sure? Can you somehow check what's going on?

**Comment by tpsatish95** [comment]
Yeah i can understand that the vectors lengths can't vary.

One thing is that, I encapsulated this line  "fromstring(fin.read(binary_len), dtype=REAL)"    with a try catch block and printed the Word and "fin.read(binary_len)"  parts out if an error pops up(In this case only "Nazira")  

I got a binary string that is the vector representation of "Nazira", as you had already suggested the binary string had some Spaces, I removed them and then tried "fromstring", This is when i got the 265D vector!

I am not even sure if the fin.read() read all the of the string or had some spaces at last that it left.

Am i supposed to remove the spaces, I even tried adding spaces to the binary strings end until it reached 300D.

Maybe the C implementation added trailing spaces that the float32 doesn't read in python.

**Comment by ziky90** [comment]
I am currently playing with word2vec models from http://evexdb.org/pmresources/vec-space-models/ and I am experiencing exactly the same problem.

I am using:
`model = gensim.models.Word2Vec.load_word2vec_format("models/PubMed-and-PMC-w2v.bin", binary=True)`

And I'm getting
`ValueError: string size must be a multiple of element size`

Is it possible that there has actually changed the format in C models? Should I consider all the models corrupted?

**Comment by gojomo** [comment]
Are you sure those files were built with the original word2vec.c? Can you tell if it's happening on the last token in the file? (This error could also indicate the source file has been truncated in the middle of a vector, somehow.) Does the file load into the original word2vec.c tools without error?

**Comment by ziky90** [comment]
I have tried to download models once again and it worked well. It seems that some of the models got corrupted during downloading.

**Comment by piskvorky** [comment]
I'm closing this -- "C tool truncating multibyte utf8 characters" was fixed in #466 , which was already released as part of gensim 0.12.3.

This seems to be unrelated to that, and hints at file corruption.
