### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by scottyli** [piskvorky/gensim#397]
Are there any pre-trained models that gensim can provide, or link to?

I know word2vec (https://code.google.com/p/word2vec/) provides some to get you started, and that this shows you how train models (https://radimrehurek.com/gensim/wiki.html).

But I was hoping there was something pretrained for LSI/LDA/Doc2Vec, (as I have a slow machine)

Thanks!

**Comment by gojomo** [comment]
A model might be of very limited utility, if applied to texts different from those it was trained on. How would you use a pre-trained model?

**Comment by brianmingus** [comment]
I am updating lsa.colorado.edu to provide pre-trained gensim models. The website presently has a variety of LSA models available.

**Comment by scottyli** [comment]
@brianmingus thanks!
