### ISSUE TITLE
small bug(?) in python (non-cython) part of word2vec

### ISSUE THREAD

**Issue by pjiangtw** [piskvorky/gensim#401]
Hi there,

I don't know if this has been brought up but in Line 121 of word2vec.py,
                # don't train on OOV words and on the `word` itself
                if (pos2 == pos):
                    train_sg_pair(model, word, word2_vocab.index, alpha)

If we don't want to train the word itself, shouldn't this be not equal to(!=) instead of equal to(==)?
This small bug is probably introduced during refactoring and left uncaught because most people use the cython version.

Best,
Pei

**Comment by liudragonfly** [comment]
And Line 119 has a little bug, too.
The for statement should be indent.

**Comment by gojomo** [comment]
Thanks for the report! These will both be fixed by the pending PR #393 , for the next relase.

**Comment by piskvorky** [comment]
#393 has been merged.

@pjiangtw , can you please check it works as expected now?
