### ISSUE TITLE
doc2vec not searching tags

### ISSUE THREAD

**Issue by saj1919** [piskvorky/gensim#402]
Hi,

I am following following to start working on doc2vec.

http://rare-technologies.com/doc2vec-tutorial/
https://radimrehurek.com/gensim/models/doc2vec.html

My code is as follows :

	#### Doc2Vec test ####
	### Enable Logging ###import logging
	logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)

	from gensim import utils
	from gensim.models import Doc2Vec
	from gensim.models.doc2vec import TaggedDocument

	### Custom line read class from file ###class MyLabeledLineSentence(object):
	    def __init__(self, filename):
		self.filename = filename

	    def __iter__(self):
		for uid, line in enumerate(open(self.filename)):
		    try:
		        parts = line.split('\t')
		        url = parts[0].strip()
		        url_id = "_".join(url.split("/")[-2:])
		        text = parts[1].strip()
		        yield TaggedDocument(utils.to_unicode(text).split(), [uid])
		    except:
		        continue

	input_file = "/home/saj1919/Music/url_data_clean.txt"sentences = MyLabeledLineSentence(input_file)
	slen = 1for s in sentences:
	    if slen < 10:
		print s
	    #print s    slen += 1
	print "#Input_Sample : "+str(slen)

	#'''model = Doc2Vec(sentences, size=100, window=10, min_count=5, sample=1e-5, negative=25, iter=20, workers=1)
	model.save("../model/doc2vec.bin")
	#'''

	model_new = Doc2Vec.load("../model/doc2vec.bin")
	print model_new.most_similar(positive=['5555'], negative=[], topn=50)

There are 6000+ documents. So uid should have 5555 as tag.
Getting following error 

	/usr/bin/python2.7 /home/saj1919/PycharmProjects/word2vec/src/doc2vec.py
	2015-07-16 19:11:33,097 : INFO : 'pattern' package not found; tag filters are not available for English
	2015-07-16 19:11:33,098 : INFO : loading Doc2Vec object from ../model/doc2vec.bin
	2015-07-16 19:11:33,372 : INFO : loading docvecs recursively from ../model/doc2vec.bin.docvecs.* with mmap=None
	2015-07-16 19:11:33,372 : INFO : setting ignored attribute syn0norm to None
	2015-07-16 19:11:33,372 : INFO : setting ignored attribute cum_table to None
	2015-07-16 19:11:33,409 : INFO : precomputing L2-norms of word weight vectors
	Traceback (most recent call last):
	  File "/home/saj1919/PycharmProjects/word2vec/src/doc2vec.py", line 46, in <module>
	    print model_new.most_similar(positive=['5555'], negative=[], topn=50)
	  File "/usr/local/lib/python2.7/dist-packages/gensim/models/word2vec.py", line 1028, in most_similar
	    raise KeyError("word '%s' not in vocabulary" % word)
	KeyError: "word '5555' not in vocabulary"

	Process finished with exit code 1

**Comment by cscorley** [comment]
The way tags are used has been changed.

Instead of `print model_new.most_similar(positive=['5555'], negative=[], topn=50)`, access the tags directly: print model_new**.docvecs.**most_similar(positive=['5555'], negative=[], topn=50)`

**Comment by gojomo** [comment]
Also: since your `uid` is a plain int from `enumerate()`, access using `5555` rather than `'5555'`.

**Comment by piskvorky** [comment]
I guess I should take down that tutorial... or add a DEPRECATED warning.

If anyone feels like writing a noob-friendly update/replacement, please let me know :)

**Comment by saj1919** [comment]
@piskvorky hey ... please don't take down tutorial ... word2vec and doc2vec are awesome things .. you can just create new documentation-example.
@gojomo @cscorley Thanks for the quick reply.

**Comment by balajikvijayan** [comment]
@piskvorky here's my gist running through the tutorial with working code: https://gist.github.com/balajikvijayan/9f7ab00f9bfd0bf56b14

As I'm learning gensim for a personal project I'd be happy to write up a full fledged noob friendly post.

**Comment by piskvorky** [comment]
Sounds good @balajikvijayan ! Consider prepending your tutorial to the [existing doc2vec notebook](https://github.com/piskvorky/gensim/blob/develop/docs/notebooks/doc2vec-IMDB.ipynb) in gensim.

That one is advanced, so placing a more gentle intro and examples at the top, leaving the advanced section near the end, makes sense to me.

**Comment by jsitruk** [comment]
Hello all, 

Thanks a bunch @cscorley, @piskvorky, and @balajikvijayan for the update!

I have been struggling for two days and finally have managed to get some sort of results with tag/sentences similarities. 

However, from what I gather, the similarities that emerge are the vector associated with the vocab word and tag/sentence, correct? 

QUESTION: My question is then, how do I get the string (i.e.: actual word and tag) associated with each similarity? 

Here is the code I am using (sorry for the formatting, I was unable to get it to work). Also, pardon the stupid question. It's just that I am pretty new at this and it is taking its toll after several days of head-scratching. 

Thanks a lot to all!


As when I run: 
    tags = [u"PROJECT_1"] # some examples
    for tag in tags:
        for w in doc2vec.docvecs.most_similar(tag,topn=200):
            print w[0], round(w[1],2)

I get: 
    PROJECT_1
    553 0.42
    1134 0.41
    199 0.41
    530 0.41

**Comment by gojomo** [comment]
@jsitruk – It's better to ask support questions in the project forum (https://groups.google.com/forum/#!forum/gensim) than on (old, closed, barely-related) github issues like this one. 

FYI, you are likely hitting the just-noticed to-be-fixed issue, that the docvecs `most_similar()` is not returning the string tags as intended, as described in this forum message: https://groups.google.com/d/msg/gensim/R8BNTxB03eU/PKbRBZi_CgAJ

(Until the fix is available, if you use all string-tags, you can look up the ints that come back from `most_similar()` in the `model.docvecs.offset2doctag` list... or switch to using plain int IDs, eg int 1 instead of string 'PROJECT_1'.)

Also since you asked about both word and doc vectors, note that even when a training mode creates both doc and word vectors (not all do), word-vecs and doc-vecs are stored separately, and a different `most_similar()` is used to search each. See this forum post for an example of mixing the two (which may not always make sense but is interesting when it works): https://groups.google.com/d/msg/gensim/Fujja7aOH6E/C3WArofWbNIJ

**Comment by jsitruk** [comment]
@gojomo Thanks so much for your prompt response. I will indeed, look into your provided feedback and, if I have any other issues, will post a new projet question as you kindly suggest! 
Once again thank you very much!
