### ISSUE TITLE
Add support for numpy arrays for `SlicedCorpus`

### ISSUE THREAD

**Issue by mattilyra** [piskvorky/gensim#413]
The `SlicedCorpus` currently only supports slicing using Python lists. It would be quite useful if the slicing could be done similar to NumPy fancy indexing. I think the changes needed are quite simple:

In `gensim/utils.py`

    def __iter__(self):
        # if hasattr(self.corpus, 'index') and self.corpus.index: # <-- this needs to be replaced to support numpy arrays
        if hasattr(self.corpus, 'index') and len(self.corpus.index) > 0:
            return (self.corpus.docbyoffset(i) for i in
                self.corpus.index[self.slice_])
         else:

in `gensim/corpora/indexedcorpus.py` (add numpy import) and change `__getitem__` from

    def __getitem__(self, docno):
        if self.index is None:
            raise RuntimeError("cannot call corpus[docid] without an index")
        if isinstance(docno, slice):
            return utils.SlicedCorpus(self, docno)
        return self.docbyoffset(self.index[docno]) 

to

    def __getitem__(self, docno):
        if self.index is None:
            raise RuntimeError("cannot call corpus[docid] without an index")
        if isinstance(docno, slice) or isinstance(docno, np.ndarray):
            return utils.SlicedCorpus(self, docno)
        return self.docbyoffset(self.index[docno])

additionally the loop in `SlicedCorpus.__len__` seems unnecessary, I think it could be replaced with

    def __len__(self):
        # check cached length, calculate if needed
        if self.length is None:
            self.length = len(self.slice_) # sum(1 for x in self) loop not needed?
        return self.length

the `self.index` needs to of course be changed to a `np.ndarray` as well, not sure what this will do to the serialisation?

**Comment by piskvorky** [comment]
Sure, sounds good, can you open a pull request?

It should be easier to comment on the proposed changes there (for example, I'm not sure you can call `len(slice)` etc).

Also, we will need good unit tests for this.

**Comment by mattilyra** [comment]
merged in PR #414
