### ISSUE TITLE
How to update doc2vec model ?

### ISSUE THREAD

**Issue by saj1919** [piskvorky/gensim#419]
Hi,

Can we update doc2vec model with new document ?
I am trying to do something like - 

    model = Doc2Vec.load("../model/doc2vec.bin")
    topic = "topic1"
    print model_new.docvecs.most_similar(positive=[topic], negative=[], topn=10),"\n\n"

    new_topic = "topic n+1"
    new_text = "some new text for topic n+1 there are n topics already in model"
    new_sentence = TaggedDocument(utils.to_unicode(new_text).split(), [new_topic])
    
    ### 
    ### Train/update model with new topic ?? how ??
    ### 

    print model_new.docvecs.most_similar(positive=[new_topic], negative=[], topn=10),"\n\n"

I tried with model.train(new_sentence) which gave me following error

    /usr/local/lib/python2.7/dist-packages/gensim/models/word2vec.py:636: UserWarning: C extension not loaded for Word2Vec, training will be slow. Install a C compiler and reinstall gensim for fast training.
    warnings.warn("C extension not loaded for Word2Vec, training will be slow. "
    2015-08-05 18:58:13,845 : INFO : training model with 1 workers on 20144 vocabulary and 300 features, using sg=0 hs=1 sample=1e-05 and negative=25
    2015-08-05 18:58:13,857 : INFO : reached end of input; waiting to finish 1 outstanding jobs
    Exception in thread Thread-1:
    Traceback (most recent call last):
    File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
    File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
    File "/usr/local/lib/python2.7/dist-packages/gensim/models/word2vec.py", line 675, in worker_loop
    if not worker_one_job(job, init):
    File "/usr/local/lib/python2.7/dist-packages/gensim/models/word2vec.py", line 666, in worker_one_job
    job_words = self._do_train_job(items, alpha, inits)
    File "/usr/local/lib/python2.7/dist-packages/gensim/models/doc2vec.py", line 617, in _do_train_job
    indexed_doctags = self.docvecs.indexed_doctags(doc.tags)
    AttributeError: 'list' object has no attribute 'tags'

Is this possible ?? How ??

**Comment by gojomo** [comment]
Doc2Vec doesn't currently support adding new tags/words to a trained (or re-loaded) model. 

You can use the `infer_vector()` method to obtain a reasonably-fit (inferred) document vector for a given bit of new text.

**Comment by saj1919** [comment]
I tried following code -

    new_url_text = "cricket kohli dhoni ipl odi test match ground stadium"
    new_sentence = TaggedDocument(utils.to_unicode(new_url_text).split(), [new_url])
    print model_new.infer_vector(new_url_text)

Getting following error

    Traceback (most recent call last):
    File "/home/saj1919/PycharmProjects/word2vec/src/doc2vec.py", line 57, in <module>
    print model_new.infer_vector(new_url_text)
    File "/usr/local/lib/python2.7/dist-packages/gensim/models/doc2vec.py", line 659, in infer_vector
    doctag_vectors=doctag_vectors, doctag_locks=doctag_locks)
    File "/usr/local/lib/python2.7/dist-packages/gensim/models/doc2vec.py", line 153, in     
    train_document_dm
    learn_vectors=False, learn_hidden=learn_hidden)
    File "/usr/local/lib/python2.7/dist-packages/gensim/models/word2vec.py", line 215, in  
    train_cbow_pair
    gb = (model.neg_labels - fb) * alpha  # vector of error gradients multiplied by the learning rate
    AttributeError: 'Doc2Vec' object has no attribute 'neg_labels'

**Comment by gojomo** [comment]
Aha. That error indicates a bug, but separately, there are two problems with what you're trying:

(1) The optimized C-version of the train routines isn't active in your installation (as also indicated by the warning in your earlier note, "UserWarning: C extension not loaded for Word2Vec, training will be slow. Install a C compiler and reinstall gensim for fast training"). Training/inference will be up to 100x slower until this is fixed. This usually requires (on Linux/OSX) reinstalling gensim, only after other local build-support for python/c is available. 

(2) `infer_vector()` takes just a list of word tokens, not a TaggedDocument.

Even after that, the remaining bug is that `neg_labels` will not have been initialized if there wasn't a call to `train()`. So, a suitable workaround until this is fixed should be to do...

    model_new.train([])

...just to force that setup, before you try inference. (However, getting the optimized C-version running will also avoid this problem, as it doesn't need that variable.)

**Comment by saj1919** [comment]
When I used `model_new.train(utils.to_unicode(new_url_text).split())` I got following error 

    Exception in thread Thread-1:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
        self.run()
      File "/usr/lib/python2.7/threading.py", line 763, in run
        self.__target(*self.__args, **self.__kwargs)
      File "/usr/local/lib/python2.7/dist-packages/gensim/models/word2vec.py", line 701, in worker_loop
        if not worker_one_job(job, init):
      File "/usr/local/lib/python2.7/dist-packages/gensim/models/word2vec.py", line 692, in        
    worker_one_job
    tally, raw_tally = self._do_train_job(items, alpha, inits)
      File "/usr/local/lib/python2.7/dist-packages/gensim/models/doc2vec.py", line 638, in _do_train_job
        indexed_doctags = self.docvecs.indexed_doctags(doc.tags)
    AttributeError: 'unicode' object has no attribute 'tags'

And it waited so long .. I had to kill the process.

Also, Can you give me steps to follow and install optimized C-version ?

**Comment by gojomo** [comment]
'infer_vector()' takes the list-of-tokens. (You got that error by providing the list-of-tokens to `train()`.)

Uninstall and reinstall gensim. The usual `pip install gensim` will automatically build the C-extensions if possible, or should show errors if that's not possible. Usually if it's not possible, it's because you don't have the necessary C-build tools and python-extension headers on your system. I don't know how to ensure those are present if you are Windows.

**Comment by saj1919** [comment]
I am using `ubuntu` and I installed `gensim` with `pip`. 
For what `C-build tools and python-extension headers` I should look for ?

I got following when I did `g++ -v` 

    COLLECT_GCC=g++ 
    COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
    Target: x86_64-linux-gnu
    Thread model: posix
    gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04)

**Comment by gojomo** [comment]
On Ubuntu I believe the apt-get packages 'build-essentials' and 'python-dev' may be enough. (But, if you get any build-errors about missing fortran stuff, they may hint other fortran/blas packages that would be necessary.)

**Comment by saj1919** [comment]
Hey, thanks. It worked.

**Comment by shrutiag95** [comment]
Slow version of gensim.models.doc2vec is being used........ i got this error even after having gcc/g++....
how can i install gcc python plugin...?
pls help me!!

**Comment by gojomo** [comment]
@shrutiag95 An old, closed, different issue is the wrong place to ask questions. Please ask on the project discussion list, <https://groups.google.com/forum/#!forum/gensim>, and describe your specific setup (python version, operating system, etc) and what you've already tried.

**Comment by StevenChen1993** [comment]
hi, everyone, when I used the infer_vector, I got the error:AttributeError: 'Doc2Vec' object has no attribute 'neg_labels'
so what should I do to set the parameters?
