### ISSUE TITLE
ZeroDivisionError using top_topics for a new document corpus from a pre trained LDA model. 

### ISSUE THREAD

**Issue by napsternxg** [piskvorky/gensim#420]
I have an LDA model which was trained on a larger corpus for extracting topics. I use the same LDA model on some new set of documents and run the top_topics routine but I am getting the ZeroDivisionError. 

Here is the stack trace:
```
In [30]: top_comment_topics = lda_model.top_topics(tfidf_model[df_comment_corpus])
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-30-29d71623725a> in <module>()
----> 1 top_comment_topics = lda_model.top_topics(tfidf_model[df_comment_corpus])

/usr/local/lib/python2.7/dist-packages/gensim/models/ldamodel.pyc in top_topics(self, corpus, num_words)
    791 
    792                     # add to the coherence sum for these two words m, l
--> 793                     coherence += numpy.log((co_doc_frequency + 1.0) / len(l_docs))
    794 
    795             coherence_scores.append((str_topics[t], coherence))

ZeroDivisionError: float division by zero

In [36]: gensim.__version__
Out[36]: '0.12.1'
```

The new corpus is smaller and has 1990 documents. I use the same TFIDF transform on this new corpus as was used on the original corpus used in training the LDA. 

I have checked that the new corpus does contain text in it. I also tried it on another data set but got the same result. However, when I run it on the original corpus then I do get some results. 
Following is the code used for creating the new corpus. The id2word, doc2bow are the same transforms which are used on the original data set.

```
df_comment_corpus = df_comment_data.message.apply(lambda x: id2word.doc2bow(tokenize(x)))
```

The log_perplexity function is working correctly on both the new corpus.

**Comment by piskvorky** [comment]
Thanks for reporting @napsternxg .

I'm not familiar with the `top_topics` functionality, but let's ping @jtmcmc and @cscorley, perhaps they remember more.

**Comment by cscorley** [comment]
(sorry for late reply)

I think that the way that the coherence measurement works requires that the training corpus is to be used. I'm not sure it's application was meant for unseen documents. Adding in a check for the zero division is no problem, but I'm not sure the results will be meaningful.

**Comment by tmylk** [comment]
Fixed in https://github.com/piskvorky/gensim/commit/de3866ed9c176f6d0a2eebf6c1248634d1c5209d
