### ISSUE TITLE
Word2Vec: Make it possible to add more complex rules for vocabulary trimming

### ISSUE THREAD

**Issue by phdowling** [piskvorky/gensim#423]
For some use cases, it may be necessary to keep certain words in the vocabulary even if their support is less than `min_count`. In my example, we're training vectors for DBpedia entities, and we'd like those to remain in the vocabulary even if their count is too low, or possibly still trim them but at a lower count than regular vocabulary words.

My proposal would be an optional parameter (`trim_rule`?) which could be perhaps a callable that returns a boolean, or some container that implements the `__contains__` method, and which is checked by word2vec when the preprocessing trims down the vocabulary. So far I've just been editing the gensim source locally and doing something like this, but that's of course a bit of a pain, and I think other might be interested in this kind of feature as well.

What do you think? Would this be a good feature to add? I'd probably be willing to implement this myself if there is interest.

**Comment by gojomo** [comment]
Some scattered thoughts: 

I've seen some cases where making a word or words immune to frequency-based trimming could be helpful – most recently, as a possible way to support the same effect as #418 with less case-specific code. 

In the realm of simple parameterizable policies, a 'must keep' list would be an easy possibility. Per-word min_count thresholds that override the global would be another. Perhaps also, similarly, a 'boost' for certain words, to treat them 'as if' they occurred N times more frequently. (How such a false-frequency would then affect other calculations, like subsampling/neg-sampling/progress-estimation, would be something to consider.)

A callable offers the most flexibility; might introduce extra serialization/deserialization gotchas. It could conceivably be called once, after the 'default' trimming has occurred but before any useful info has been discarded, to do a bulk edit of the surviving vocabulary (maybe both adding & removing words). Or it could be called once per word, and in such a case might offer a sort of 3-valued decision: 'must keep', 'must discard', or 'do default'. 

Does your current local patch take advantage of the scan_vocab() / scale_vocab() / finalize_vocab() split?

**Comment by piskvorky** [comment]
If we extend this functionality, we'll definitely go with something as general as possible (callable).

It doesn't look complex, and seems fully backward compatible, so I'm in favour of this.

Re. the callable API: again, something as generic as possible. How about a signature of `(word=unicode, freq=int) -> bool`? Or the 3-valued decision @gojomo proposes: `(word=unicode, freq=int) -> {KEEP=0, DISCARD=1, DEFAULT=2}`.

**Comment by phdowling** [comment]
I personally think 3-valued output would be good, it makes it easier to add special case rules without having to also handle the normal case each time.

My current local patch doesn't implement this as a callable, I just wrote the rules straight into the word2vec source, but that was basically before the recent changes there, so now it's not really mergeable. I probably need to train a new model with DBpedia entities soon though, so I'll see if I can get this implemented with the new version of gensim and the callable solution.

**Comment by phdowling** [comment]
Would we need separate rules for `utils.prune_vocab` and `scale_vocab`?

**Comment by gojomo** [comment]
To answer the question here, any `prune_vocab` rules would logically have to be different, given their interim/probabilistic application. *But,* that'd make things complicated, and I suspect sophisticated users won't be using mid-scan pruning at all, because they'll have enough memory to apply an intentional policy at the end. (Other comments on the PR #434.)

**Comment by dedcode** [comment]
Hi, I am not sure I understand the new API. Specifically how to define trim_rule.
Lets say I'd like to keep certain words, e.g., ```word.startswith("DBPEDIA_ID/")```, and fallback to ```min_count``` otherwise
What would be the trim_rule here?
Thanks

**Comment by phdowling** [comment]
See PR #434. For that case, your rule could be:
```
def rule(word, count, min_count):
    if word.startswith("DBPEDIA_ID/"):
        return gensim.utils.RULE_KEEP
    else:
        return gensim.utils.RULE_DEFAULT 
```

**Comment by tmylk** [comment]
Closing as implemented
