### ISSUE TITLE
SystemError: error return without exception set

### ISSUE THREAD

**Issue by ziky90** [piskvorky/gensim#437]
I am using `gensim.utils.SaveLoad` and when I try to save the object, I am getting the following error:

```
<ipython-input-8-608faf1b41bc> in <module>()
----> 1 mec.save("data/model_bayes.pkl")

/Users/zikes/.virtualenvs/elastic/lib/python2.7/site-packages/gensim/utils.pyc in save(self, fname_or_handle, separately, sep_limit, ignore, pickle_protocol)
    480         except TypeError:  # `fname_or_handle` does not have write attribute
    481             self._smart_save(fname_or_handle, separately, sep_limit, ignore,
--> 482                              pickle_protocol=pickle_protocol)
    483 #endclass SaveLoad
    484

/Users/zikes/.virtualenvs/elastic/lib/python2.7/site-packages/gensim/utils.pyc in _smart_save(self, fname, separately, sep_limit, ignore, pickle_protocol)
    353                                        compress, subname)
    354         try:
--> 355             pickle(self, fname, protocol=pickle_protocol)
    356         finally:
    357             # restore attribs handled specially

/Users/zikes/.virtualenvs/elastic/lib/python2.7/site-packages/gensim/utils.pyc in pickle(obj, fname, protocol)
    899     """
    900     with smart_open(fname, 'wb') as fout: # 'b' for binary, needed on Windows
--> 901         _pickle.dump(obj, fout, protocol=protocol)
    902
    903

SystemError: error return without exception set
```

It seems to me that the problem is probably related to some problem in cPickle, particularly to some problem with pickling of big numpy arrays. But does anyone experienced this before? Is there some workaround that can be done?

When I try to pickle the object with standard pickle, then everything works fine.

**Comment by piskvorky** [comment]
`_pickle` is just an alias for "standard pickle"; or how is it different?

**Comment by ziky90** [comment]
`_pickle` is in my case alias for cPickle, but interesting is that when I use either pickle or cPickle in a way `pickle.dump(object, path)`, then everything works fine, but when I do `object.save()`, then I got the stack trace above.

It looks very similar to #161 , but I use the latest pickle, cPickle, numpy, scipy and gensim, so I assume that this should have been already fixed in previous versions?

**Comment by piskvorky** [comment]
Strange. But it should be easy to debug, as `save()` is just a thin wrapper around `pickle.dump()` (you can see it in your stacktrace above). Maybe the `protocol` parameter makes the difference?

**Comment by ziky90** [comment]
@piskvorky You were right, it was because of the protocol. It worked with 0, but not with 2.

**Comment by piskvorky** [comment]
Interesting. IIRC, protocol 0 is very chatty, producing very large files. So I'm not too keen on switching the  default from 2 to 0.

But big numpy arrays should be automatically saved in a different way, using `numpy.save`, not pickle. See the `separately` parameter in [save() API](http://radimrehurek.com/gensim/utils.html#gensim.utils.SaveLoad.save). So your problem shouldn't even happen.

Can you say a little more about your use case, what objects you're storing, why `separately` doesn't work?

**Comment by tmylk** [comment]
Pinging @ziky90 - do you remember the details here or should this be closed?

**Comment by ziky90** [comment]
I remember that I had this problem when I had really huge models 50+ GB.
Currently I don't experience this problem with any model that I use.

**Comment by tmylk** [comment]
@ziky90 are you ok if this is closed?

**Comment by ziky90** [comment]
Yes I am.
