### ISSUE TITLE
Can not compile word2vec_inner.pxy with gensim0.12.1

### ISSUE THREAD

**Issue by chenjifan1991** [piskvorky/gensim#439]
Hi everyone, I've updated my gensim to 0.12.1 recently and find the word2vec.pyx file could not be compiled by cython.

I got errors like
![image](https://cloud.githubusercontent.com/assets/3676599/9518038/65c35e18-4ce6-11e5-83d3-bf01c445886d.png)

and I can't find the definition of 'REAL_t' in the file word2vec.pyx.
Has anyone of you compiled this file successfully ?
I've tried different platforms and got the same errors.

**Comment by piskvorky** [comment]
Hi, `REAL_t` is defined at the beginning of this file, at [this line](https://github.com/piskvorky/gensim/blob/develop/gensim/models/word2vec_inner.pyx#L43).

So I'm not sure what the problem is -- what's your version of cython?

**Comment by piskvorky** [comment]
What's your OS + cython version?

**Comment by chenjifan1991** [comment]
Oh, I find that I haven't include the PXD file which causes the problem, I downloaded this file and solved it.

Thank you anyway.
