### ISSUE TITLE
Using Portuguese Wikipedia

### ISSUE THREAD

**Issue by rodolphorosa** [piskvorky/gensim#442]
Hi.

I'm trying to use gensim in an assignment at my university at Brazil and I have to use a dataset of portuguese words and, for this, I downloaded the portuguese wikipedia articles. However, I'm getting errors due to the fact the words have diacritics and even after I set the encoding to utf-8, it looks like gensim doesn't recognize them correctly. I have used codecs.open as well, but it keeps not working.

How can I fix that?

PS.: sorry for the bad english :)

**Comment by piskvorky** [comment]
Gensim generally uses unicode to represent texts (words), so portuguese characters are fine. Peopel even use gensim for languages like japanese, korean or chinese.

Can you show what errors you're getting? (exception traceback + log at DEBUG level)

**Comment by rodolphorosa** [comment]
I expressed myself wrong. It is not an error exactly. The problem is that word2vec is generating strange characters where there is a diacritic. For exemple, for the word "ciência", it generates "ci\xencia". I set the encoding, however it looks like it doesn't make any difference.

Thanks for answering that fast and sorry if the question is a little bit noobie, but not getting it fixed is driving me nuts.

**Comment by piskvorky** [comment]
Aha, so you're using word2vec. Word2vec accepts unicode, just like other models in gensim.

In other words, when you prepare the `sentences` input for word2vec, convert your words to unicode. Gensim doesn't "generate" any other words, it accepts what you give it.

**Comment by gojomo** [comment]
I think you are in fact reading and representing the strings properly as unicode – it's just your output that's choosing to use an 'escaped' representation. So the issue is how you're displaying/reviewing the python strings.  

For example,  are you actually viewing the `repr()` of the strings, as in a python interpreter or by explicitly writing the `repr()` to a file? 

Consider the following set of interactions with the python interpreter:

    $ python
    Python 2.7.10 (default, Jul 14 2015, 19:46:27)
    [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>>
    >>> u = u'ciência'
    >>>
    >>> u
    u'ci\xeancia'
    >>>
    >>> print(str(u))
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xea' in position 2: ordinal not in range(128)
    >>>
    >>> print(u)
    ciência
    >>>
    >>> with open('test.tmp','w') as f:
    ...     f.write(u)
    ...
    Traceback (most recent call last):
    File "<stdin>", line 2, in <module>
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xea' in position 2: ordinal not in range(128)
    >>>
    >>> with open('test.tmp','w') as f:
    ...     f.write(str(u))
    ...
    Traceback (most recent call last):
    File "<stdin>", line 2, in <module>
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xea' in position 2: ordinal not in range(128)
    >>>
    >>> with open('test.tmp','w') as f:
    ...     f.write(repr(u))
    ...
    >>>

Seems like it works! But examining the file outside Python (as if by 'cat' in a UTF-8 aware terminal) reveals the string has been written as if it were a python literal, in ASCII source code, with non-ASCII characters as backslash-escaped hex values:

    u'ci\xeancia'

Back in the interpreter, we need to be explicit about the writing encoding:

    >>> import codecs
    >>> with codecs.open('test.utf8','w',encoding='utf8') as f:
    ... f.write(u)
    ...

Now examining the file outside python:
    ciência

(If you can't reproduce the desired effect from these examples, please be explicit about exactly what code you are using to read & display/write your words.)

**Comment by rodolphorosa** [comment]
I'm trying to read the words from a file. I used this to read the file with the correct encoding:
````
documents = codecs.open('wiki.txt', 'r', 'utf-8')
````
When I try to print the vocabulary, I see that the words that were written with diacritics come that way:

```
u't\xe9rmica': <gensim.models.word2vec.Vocab object at 0x03B32810>
```
The original word was 'térmica'.

When I use

```
documents = open('wiki.txt')
```
instead, the result comes that way:

```
'tã\xa9rmica': <gensim.models.word2vec.Vocab object at 0x03B33790>
```
I'm not writing the words in another file, only printing them in the console.
For the time being, I'm just making some tests, and I have to have it solved before starting doing the real stuff.

**Comment by cscorley** [comment]
The print() function will call repr on objects when contained in other objects (like a dictionary):

```python
>>> class ButtorBug:
...     def __str__(self):
...         return "Bug!"
...     def __repr__(self):
...         return "Butt!"
...
>>> b = ButtorBug()
>>> repr(b)
'Butt!'
>>> str(b)
'Bug!'
>>> print(b)
Bug!
>>> print([b, b, b,])
[Butt!, Butt!, Butt!]
```

**Comment by rodolphorosa** [comment]
The problem is in the generated vocabulary. The words are stored with strange characters in the model. For example, for the word 
```
ciência
```
console says it is not in the vocabulary, once the word was stored as
```
u'ci\xeancia'
```
instead. I think Word2Vec is not recognizing the words properly somehow :(

**Comment by gojomo** [comment]
It looks to me like they're stored fine, but the code you're running to display them is showing them as escaped literals. 

If the "console says it is not in the vocabulary", show us the console code you're using to get that answer. (You may be looking it up with the wrong lookup-string.) If you believe "the word was stored as [something wrong]", show us the console code you've used to check what's stored. 

Note that the python literal `u'ci\xeancia'` *is* the string `ciência`, just displayed a different way, as if for an ASCII terminal or source file. 

Look over – and try in your console! – the following to get the general gist of it:

    >>> 
    >>> s = u'ciência'
    >>> s
    u'ci\xeancia'
    >>> print(repr(s))
    u'ci\xeancia'
    >>> print(s)
    ciência
    >>> s == u'ciência'
    True
    >>> s == u'ci\xeancia'
    True
    >>> u'ciência' == u'ci\xeancia'
    True
    >>> s[2]
    u'\xea'
    >>> print(repr(s[2]))
    u'\xea'
    >>> print(s[2])
    ê
    >>>

**Comment by rodolphorosa** [comment]
Here's the code.
In it, I searched for the word 'galáxia'.

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from gensim.models import Word2Vec
import gensim, logging, codecs
from pprint import pprint
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)

documents = codecs.open('wiki.txt', 'r', 'utf-8')

stoplist = set('a e o as os ao aos um uma uns umas de do da dos das com para sem se em no na nos nas que ou por'.split())
sentences = [[word for word in document.lower().split() if word not in stoplist] for document in documents]

from collections import defaultdict
frequency = defaultdict(int)
for text in sentences:
     for token in text:
         frequency[token] += 1

sentences = [[token for token in text if frequency[token] > 1]
          for text in sentences]

model = Word2Vec(sentences, min_count=5)

pprint(model.vocab)

print(model.most_similar(positive = ['galáxia'], topn=1))
```

'galáxia' was recognized as:
```
u'gal\xe1xia': <gensim.models.word2vec.Vocab object at 0x03AA5B70>
```

Here's the traceback:
```
Traceback (most recent call last):
  File "D:\UFRRJ\TCC\teste_gensim_pt.py", line 24, in <module>
    print(model.most_similar(positive = ['galÃ¡xia'], topn=1))
  File "C:\Python27\lib\site-packages\gensim-0.12.1-py2.7-win32.egg\gensim\models\word2vec.py", line 1088, in most_similar
    raise KeyError("word '%s' not in vocabulary" % word)
KeyError: "word 'gal\xc3\xa1xia' not in vocabulary"
```

**Comment by cscorley** [comment]
What happens when you replace
```python
 print(model.most_similar(positive = ['galáxia'], topn=1))
```

with

```python
print(model.most_similar(positive = [u'galáxia'], topn=1))
```
?

**Comment by rodolphorosa** [comment]
I seems to work. It does not show the error.
