### ISSUE TITLE
LdaMulticore error in multiprocessing

### ISSUE THREAD

**Issue by lucidfrontier45** [piskvorky/gensim#445]
Hi. I tried to build an LDAModel by LdaMulticore as follows.

```python
import pymongo
import numpy as np
import gensim

db = pymongo.MongoClient("192.168.254.226:37017").documents
ret = list(db.parsed.find({}, {"_id":1, "words":1, "title":1}).limit(150000))
documents = [r["words"] for r in ret]
print("data was loaded")

word_dict = gensim.corpora.Dictionary(documents)
print("dictionary created")

corpus = [word_dict.doc2bow(doc) for doc in documents]
print("corpus created")

model = gensim.models.LdaMulticore(corpus=corpus, num_topics=500,
    id2word=word_dict, iterations=200, workers=3)
print("lda done")

model.save("/tmp/test/model")
```

 When data is few, it ran OK. However when I increase data, it crashed in multiprocessing.

```python
Traceback (most recent call last):
  File "/home/isc/anaconda/envs/gensim/lib/python3.4/multiprocessing/queues.py", line 248, in _feed
    send_bytes(obj)
  File "/home/isc/anaconda/envs/gensim/lib/python3.4/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/isc/anaconda/envs/gensim/lib/python3.4/multiprocessing/connection.py", line 399, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
```

Any idea? I use python3.4 of Anaconda distribution and gensim 0.12 installed with pip.
Thank you.

**Comment by piskvorky** [comment]
What is your dictionary size? (or paste your entire log here)

My guess would be that filtering too frequent/infrequent words both improves performance (less memory, faster training) and quality (better topics).

Have a look at [corpus streaming](http://radimrehurek.com/gensim/tut1.html#corpus-streaming-one-document-at-a-time) and [word frequency filtering](http://radimrehurek.com/gensim/corpora/dictionary.html#gensim.corpora.dictionary.Dictionary.filter_extremes).

**Comment by lucidfrontier45** [comment]
Hi @piskvorky thank you for reply.

>What is your dictionary size? (even better, paste your entire log either here or using gist)

The above was the whole trace. No other error messages.
The dictionary contains 306938 words according to `len(word_dict.token2id)`

>Have a look at corpus streaming and word frequency filtering. The way you're using gensim is very suboptimal, data streaming is a big part of it.

I don't understand why corpus streaming can improve performance or fix the above error.
Since LDA is an iterative algorithm, the whole corpus must be on memory for efficient iteration otherwise they must be loaded from disk or network for each iteration.

**Comment by piskvorky** [comment]
LDA in gensim is a streamed (online) algorithm.

To turn on logging, see instruction at the top of the [tutorial page](http://radimrehurek.com/gensim/tut1.html#corpus-streaming-one-document-at-a-time).

**Comment by lucidfrontier45** [comment]
>That's suspiciously close to 2**30, and it looks like multiprocessing has problems sending large models.

Your right. I made `num_topics` to 100 and the error was gone. I'll try filtering words next.

I still have one question. Is there any documented limitation of `num_words` x `num_topics`?
As you said 2**30 GB will cause `multiprocessing` problems.

**Comment by piskvorky** [comment]
There is no limitation in gensim. It's a problem with `multiprocessing` (Python's built-in library), which fails to serialize large objects to send between processes.

If you really want a large model, use LdaModel (not LdaMulticore). That one doesn't use multiprocessing, so it's not affected by this limitation.

**Comment by cscorley** [comment]
FWIW, you can get numpy to utilize multiple cores for it's operations by ensuring it's compiled with openmp directives enabled. This would allow you to use the LdaModel while also getting some juice from your other cores.  However, there may be tradeoffs for you in doing that: http://stackoverflow.com/questions/15414027/multiprocessing-pool-makes-numpy-matrix-multiplication-slower

**Comment by lucidfrontier45** [comment]
@piskvorky 
thank you a lot for help!

@cscorley 
Recent anaconda is shipped with openblas but multi-threading looks not enabled. Nevertheless I can build numpy against other openblas for anaconda.
