### ISSUE TITLE
Integrate visualization into gensim

### ISSUE THREAD

**Issue by piskvorky** [piskvorky/gensim#452]
Explore the interface of pyLDAviz. Add direct support for visualizing models, or for export to pyLDAviz.

CC @rohit12

**Comment by rohit12** [comment]
Tested pyLDAvis with gensim. 20newsgroups working fine. Will test it out on other data sets.

**Comment by piskvorky** [comment]
Great! You commit an ipython notebook that demonstrates your experiment(s)?

That way, we can discuss your results directly.

**Comment by tmylk** [comment]
@piskvorky Is the original Pyldavis ipynb good enough? it uses gensim
http://nbviewer.ipython.org/github/bmabey/pyLDAvis/blob/master/notebooks/pyLDAvis_overview.ipynb

**Comment by piskvorky** [comment]
If the support in pyLDAviz is working, I suppose nothing else is needed from gensim's side.

I forgot what the issues there were, maybe there weren't any and this was just a confirmation experiment.

**Comment by tmylk** [comment]
Rahul has reproduced PyLDAVis notebook, so closing
