### ISSUE TITLE
vocabs and sentence labels in doc2vec

### ISSUE THREAD

**Issue by nick-magnini** [piskvorky/gensim#453]
Hi,

I've trained a doc2vec model based on your tutorial. At first I realized that I don't have SENT_x in my model. Then after searching I realized that model.docvecs and model are different. So basically if I want to find the most similar sentences to SENT_x then I should use:
model.docvecs.most_similar(positive=['SENT_0'])
This will retrieve only sentences.

If I want to get the most similar words then I have 
model.most_similar(positive=['Gold'])
which will result in n similar words to Gold.

Is there anyway I can use the same model to find similar sentences to a word or similar word to a sentences? Or is there any way I can model them in the same dimension? Thanks.

**Comment by gojomo** [comment]
See similar question addressed on list: https://groups.google.com/d/msg/gensim/Fujja7aOH6E/C3WArofWbNIJ
