### ISSUE TITLE
Comparing LDA between gensim and sklearn

### ISSUE THREAD

**Issue by tmylk** [piskvorky/gensim#457]
Just sharing results of some comparisons that I ran, no issues here.

The great sklearn package has [recently added an LDA implementation](https://github.com/scikit-learn/scikit-learn/pull/3659) which is easy to use with sklearn pipelines. It was interesting to compare it to gensim. This is based on @chyikwei 's test script. Thanks a lot for sharing it!

Sklearn and gensim basically agree, only one [minor issue](https://github.com/piskvorky/gensim/pull/456) found. Results of comparison are in [this spreadsheet](https://docs.google.com/spreadsheets/d/1TQxv_i3w18uQCDKYAywNbw-z4SuEQEhvOsM-KUykFII/edit?usp=sharing).

**Validation method**. If perplexities are within 0.1% then I wouldn't worry, the implementations are the same to me.

The perplexity bounds are not expected to agree exactly here because bound is calculated differently in gensim vs sklearn. Sklearn initialises doc_topic_distr aka q(theta|gamma) as np.ones while gensim uses random.gamma. Also sklearn using cython which creates numerical 6th dp differences.

**Results.**

*Batch mode.* With decay = 0, the two implementations agree. Tested 5 M-steps on 10k documents.

*Mini-batch mode aka 'online'.* Single core gensim LDA and sklearn agree up to 6dp with decay =0.5 and 5 M-steps.

However comparing multicore LDA and gensim is harder as the parallelisation models are different.
Gensim is fully async as in this [blog post](http://rare-technologies.com/multicore-lda-in-python-from-over-night-to-over-lunch/) while sklearn doesn't go that far and parallelises only E-steps. They agree after figuring out right parameters to run with same number of docs per thread in each, see spreadsheet for single M-step test results.

*Performance*
Sklearn with cython is 3 times faster than gensim due to using cython.
After re-writing sklearn's cython functions in Python I got a 2x slow down.

The test code is in this [gist](https://gist.github.com/tmylk/b71bf7d3ec2f203bfce2). The heavily logged versions of sklearn and gensim are [here](https://gist.github.com/tmylk/4da77c179adf7075ab09).. They are good to make sure intermediate steps agree in BeyondCompare

**Comment by cscorley** [comment]
One new thing I noticed that sklearn implements that gensim does not is an early break in the passes if the bound has not changed much. I know that you set a pretty low passes (=5), but did this influence your timing?

**Comment by piskvorky** [comment]
Could we use the same cython code in gensim as well?

I mean, fully optional (just like with word2vec). But if it's already been tested in sklearn, it should be a fairly trivial op to plug the same cython routines into gensim, to get the same speed up if the C-module compiles (and a fall back to existing code if not).

**Comment by tmylk** [comment]
Cython implementation attempt in https://github.com/piskvorky/gensim/pull/568

**Comment by breschke** [comment]
Note, perplexity is currently broken in sklearn 0.18 and 0.18.1 https://github.com/scikit-learn/scikit-learn/pull/7992. I believe sklearn 0.17.1 will replicate these comparisons.

**Comment by LeoPetrini** [comment]
@breschke :  do you know if perplexity fixed as of 18.2 ?

**Comment by roxanaatt** [comment]
for some reason LDA in sklearn is dead slow for me and it takes at least a week to run LDA. What do you think the reason would be? I'm thinking that maybe sklearn on my computer is using only one core! How can I make it parallel??

**Comment by chyikwei** [comment]
@roxanaatt 
For parallel computing, you can change `n_jobs` parameter.
Also, try set `learning_method` to `online` and increase `batch_size`.

Reference:
http://scikit-learn.org/stable/modules/generated/sklearn.decomposition.LatentDirichletAllocation.html
