### ISSUE TITLE
dict.iteritems() usage breaks "keywords" function in python 3

### ISSUE THREAD

**Issue by d10genes** [piskvorky/gensim#459]
Calling `gensim.summarization.keywords` in python3 results in `AttributeError: 'dict' object has no attribute 'iteritems'`.

Looks like there are offenders [here](https://github.com/piskvorky/gensim/blob/485d024e119d0ff818ea6651042748a3bff21081/gensim/summarization/keywords.py#L35) and [here](https://github.com/piskvorky/gensim/blob/485d024e119d0ff818ea6651042748a3bff21081/gensim/summarization/keywords.py#L114). I assume these should be fixed with six.iteritems?

**Comment by piskvorky** [comment]
Indeed! Thanks for reporting.

Can you put together a PR fix? And, ideally, also add a simple unit test for `keywords`, so we can catch such things more easily...

**Comment by d10genes** [comment]
Sure, the iteritems fix should be easy enough, but to get the test working, I'm having trouble figuring out what to do with the `.decode("utf-8")` call [here](https://github.com/piskvorky/gensim/blob/485d024e119d0ff818ea6651042748a3bff21081/gensim/summarization/keywords.py#L159).

It works fine with python 2, but in python3, I'm getting `AttributeError: 'str' object has no attribute 'decode'`. I'm not an expert with string encoding, so I'm not even sure what case `decode` is supposed to cover, but FWIW dropping the `decode` call doesn't change the results in python 2 for the an ascii example input I tried. (in python 2, calling `decode` with some unicode input failed with `UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 1: ordinal not in range(128)`. So maybe the purpose of the call is to ensure ascii-only input?)

Any suggestions? Or should I open a separate issue?

**Comment by piskvorky** [comment]
We want to convert all text inputs to **unicode** -- use `gensim.utils.to_unicode`. It accepts both utf8 and unicode, so it's safe for whatever the user throws at us.

Similarly, on output, we convert to utf8 using `gensim.utils.to_utf8`. Again, it accepts both utf8 and unicode as input, so it's safer.

**Comment by d10genes** [comment]
I'm not really understanding the test failure [here](https://travis-ci.org/piskvorky/gensim/builds/81809210), is that just a random error or did my code really affect word2vec?

**Comment by piskvorky** [comment]
Random, ignore.

@gojomo still the same problem with doc2vec tests.
