### ISSUE TITLE
Bound doubt

### ISSUE THREAD

**Issue by jcapde87** [piskvorky/gensim#464]
Hi, 

I was checking the code of the LDA implementation, since I have detected it mismatches mine and the following doubt it came up:

When computing the bound, I understand steps: 
\# E[log p(theta | alpha) - log q(theta | gamma)];
\# E[log p(beta | eta) - log q (beta | lambda)];

but do not understand,
\# E[log p(doc | theta, beta)]

In my opinion and according to Hoffman&Blei'2010 paper (Eq. 4) ,  https://www.cs.princeton.edu/~blei/papers/HoffmanBleiBach2010b.pdf
we  would need to compute: 
\# E[log p(w, z | theta, beta) - log q(z | phi)]
Why is that not the case here?

Many thanks, 
Joan

**Comment by piskvorky** [comment]
Hello Joan, open ended questions like this are better served on the [mailing list](https://groups.google.com/d/forum/gensim) (easier for other people to find and participate).

Can you move the discussion there?

**Comment by jcapde87** [comment]
Totally agree @piskvorky I did not about the mailing list. Move it there. Thks.
