### ISSUE TITLE
'corpus2dense' method doesn't work with small 'num_terms' for HDP

### ISSUE THREAD

**Issue by nikicc** [piskvorky/gensim#477]
When using HDP model in an iteratively fashion (using update) and trying to get numpy matrix with small number of terms (`num_terms`) the call `gensim.matutils.corpus2dense(corpus, num_terms=3).T` raises the following error:
`     IndexError: index 3 is out of bounds for axis 1 with size 3`

The minimal example that causes this error is pasted below. I believe the problem is in the file `matutils.py` in line `209` (I am using `gensim (0.12.2)`). For small number of terms the `list(doc)` contains indices larger than the length of `result` and consequently it crashes.

*********************************************************************************
The code that reproduce this error is the following:
```    
import gensim
from gensim import corpora, models

documents = [
    "Human machine interface for lab abc computer applications.",
    "A survey of user opinion of computer system response time.",
    "The EPS user interface management system",
    "System and human system engineering testing of EPS",
    "Relation of user perceived response time to error measurement",
    "The generation of random binary unordered trees",
    "The intersection graph of paths in trees",
    "Graph minors IV Widths of trees and well quasi ordering",
    "Graph minors A survey",
]

text = []
for sent in documents:
    text.append(sent.split())

dictionary = corpora.Dictionary(text)
corpus = [dictionary.doc2bow(t) for t in text]

hdp = models.HdpModel(corpus=[[]], id2word=dictionary)
hdp.update(corpus)
corpus = hdp[corpus]

matrix = gensim.matutils.corpus2dense(corpus, num_terms=3).T
print(matrix)
```

**Comment by piskvorky** [comment]
Why do you set `num_terms=3`?

If I recall correctly, the dictionary on that example toy corpus had more than 10 terms. (since you don't even lower case the texts, probably more than 20).

**Comment by nikicc** [comment]
Maybe my understanding of HDP is wrong. Is not the `num_terms` like the number of topics that you want to use to represent your data (as the number of topics for LDA)?

As I understand it, after using the HDP model on the `corpus`, it is the matrix of documents and theirs associations with different topics. Is that right?

What I then want is to do is to get out the matrix of documents in their "topical representation".

**Comment by piskvorky** [comment]
No, the `num_terms` parameter in `corpus2dense(corpus, num_terms)` just says how many features there are in your corpus. It has nothing to do with HDP (the same `corpus2dense` call can be used on tfidf corpora, LSI corpora etc).

Max number of topics for HDP is controlled in the HdpModel constructur, setting a maximum values if I recall correctly... @jesterhazy how exactly does it work?

**Comment by jesterhazy** [comment]
HDP has two maximum values for topics, one to control corpus-level topics
and the other for document-level topics. They are set using HdpModel's T
and K constructor parameters.

Keep in mind that these values don't control the number of topics the way
LDA's topic parameter does. You should set them well above the actual
number of topics you expect to be in the corpus/in each document, and
expect the model to leave some of them unused. Experiment with gamma and
alpha to produce models with more/less topics at each level.

**Comment by nikicc** [comment]
@piskvorky @jesterhazy thanks, this makes sense. I will take a closer look at HDP model parameters.
