### ISSUE TITLE
Make aclImdb/alldata-id.txt  availible to Doc2vec notebook can be run

### ISSUE THREAD

**Issue by cbonnett** [piskvorky/gensim#488]
I can not seem to find the aclImdb/alldata-id.txt  that is used in the Doc2vec. 
Am I blind ? or Is the file not available ?

**Comment by cbonnett** [comment]
Or a link to where one can get the file ?

**Comment by gojomo** [comment]
Cell #1 of the notebook will fetch (and unpack) the data if not present at the expected location – see the line:

    wget --quiet http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz

(I've just checked, it's still available at that URL.)

If you don't have `wget` installed, but do have `curl`, you should be able to replace `wget --quiet` with `curl -O`.

**Comment by cbonnett** [comment]
So I was blind ! Thanks for the clarification.

**Comment by rahul-ka** [comment]
Do you have the original tar file that you downloaded? I think the download has since been changed and the notebook isn't working as intended anymore.

**Comment by gojomo** [comment]
What error are you getting? (It appears to me <http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz> is still available.)
