### ISSUE TITLE
Doc2Vec - Saving in Word2vec Format Error

### ISSUE THREAD

**Issue by newterminator** [piskvorky/gensim#498]
![doc2vec_save](https://cloud.githubusercontent.com/assets/5087437/10680854/a73499ac-78f1-11e5-8ecd-bd9737ab4185.png)

As seen above: 
Saving the dbow and dm-mean models in word2vec binary format does not cause any issues, however doing the same with dm-concat model throws this error...

**Comment by gojomo** [comment]
The following works for me, so it doesn't appear to be an inherent problem with all `dm_concat=1` models:

```
In [1]: from gensim.test.test_doc2vec import DocsLeeCorpus
In [2]: from gensim.models.doc2vec import Doc2Vec
In [3]: model = Doc2Vec(DocsLeeCorpus(), dm=1, dm_concat=1)
In [4]: model.save_word2vec_format('test.delme')
```

Maybe there's a code path (in gensim code or your own) where that model's `syn0` is inadvertently nulled? Can you check at some earlier points in your training that the model has a `syn0`? (It is a normal part of that model just like the others...)

**Comment by newterminator** [comment]
Hi @gojomo , May I ask you what is a model's - syn0 ?

**Comment by newterminator** [comment]
Hi @gojomo , May I ask you what is a model's syn0 ?

The code that I have in the ipython notebook is exactly the same as in the example notebook posted [here](https://github.com/piskvorky/gensim/blob/develop/docs/notebooks/doc2vec-IMDB.ipynb). Only difference is that my dataset is 893 MB in size. The code, line to line is same, except for the part to mention the directory path to the dataset.

I ran the example notebook with the imdb dataset and the word2vec binary format gets saved for the dm_concat model as well, and also loads without errors. 

So I am not sure as to what might be causing the problem.

**Comment by gojomo** [comment]
Practically, the `syn0` is the array holding al the word-vectors in-training.

I also just tried the example notebook with the `dm=1, dm_concat=1` model, it saved just fine. 

Does the model work for vector-lookup and similarity testing beforehand? Do you get the error on repeated runs? Do you get it if you try the save earlier – eg, just after `build_vocab()`, just after training, etc? 

`syn0` should exist after `build_vocab()`. If it doesn't exist later, then some step between `build_vocab()` and your save must have cleared it...

**Comment by newterminator** [comment]
Hi @gojomo , Thank you for responding to my query and explaining `syn0`.

Yes the `syn0` for `simple_model[0]` or in other words for the `dm_concat=1` model does not exist after `build_vocab()`. 

So I am going to re-run the notebook again and hopefully it works as expected.

**Comment by newterminator** [comment]
Hi @gojomo , I got the notebook running again and I got the arrays(syn0) for all the models. So definitely like you mentioned some where in the previous run some step must have cleared the values of dm_concat model. Thank you once again for helping me clear this issue up.
