### ISSUE TITLE
Don't allow saving incomplete word2vec objects

### ISSUE THREAD

**Issue by piskvorky** [piskvorky/gensim#499]
From a [mailing list report](https://groups.google.com/forum/#!topic/gensim/1z0S8TBnkUA):

Currently, when a word2vec object is loaded from the C tool via `load_word2vec_format`, it can be saved with `model.save()`. But loading such saved model back with `load()` results in an error. Vital pieces of the object are missing, the C format is incomplete.

This is undesirable and unintuitive behaviour.

Solution:

* either refuse to save: throw an explicit exception that necessary structures are missing
* or (better) make those structures not necessary. If the object serves its purpose after `load_word2vec_format`, without those structures, it might as well serve its purpose after `load`, again without those structures.

**Comment by ziky90** [comment]
Issue was fixed in #540 and #543 so I guess that we can close this.
