### ISSUE TITLE
OSX build

### ISSUE THREAD

**Issue by tmylk** [piskvorky/gensim#504]
OSX build in https://github.com/MacPython/gensim-wheels

**Comment by piskvorky** [comment]
Apparently OS X builds can be easily added to Travis as well: 
https://github.com/spotify/annoy/pull/118/

**Comment by tmylk** [comment]
It's easy for C project like Annoy but unfortunately Python support is more tricky

**Comment by tmylk** [comment]
That PR wasn't merged in as "Python builds are not available on the osx" https://docs.travis-ci.com/user/languages/python
