### ISSUE TITLE
Advice is needed

### ISSUE THREAD

**Issue by Grinshpun** [piskvorky/gensim#506]
Relatively new to the Topic Model. When I produce my topics they seem to overlap an awful lot, which appears counter-intuitive on one hand, and somewhat logical on the other (please see example below).  So the two questions I have are: 
1. Is there a generally accepted way to measure the "purity" or overlap of a topic?
2. Is there a way in genism to generate topics with minimal or no overlap?

['0.015*odeen + 0.015*gladia + 0.011*dua + 0.010*tritt + 0.009*giskard + 0.007*lamont + 0.007*solaria + 0.007*denison + 0.006*pump + 0.005*delmarre',
 '0.023*odeen + 0.017*dua + 0.014*tritt + 0.013*lamont + 0.012*denison + 0.010*gladia + 0.009*pump + 0.007*giskard + 0.005*para + 0.005*amadiro',
 '0.011*odeen + 0.011*gladia + 0.010*tritt + 0.010*giskard + 0.008*dua + 0.006*denison + 0.006*hardin + 0.006*solaria + 0.005*lamont + 0.005*pump',
 '0.022*gladia + 0.012*delmarre + 0.011*giskard + 0.010*solaria + 0.010*odeen + 0.009*tritt + 0.008*dua + 0.007*amadiro + 0.006*solarian + 0.005*jander',
 '0.031*giskard + 0.030*gladia + 0.022*amadiro + 0.018*jander + 0.013*vasilia + 0.012*chairman + 0.010*solaria + 0.009*auroran + 0.008*gremionis + 0.006*solarian',
 '0.014*giskard + 0.013*amadiro + 0.013*gladia + 0.008*hardin + 0.007*jander + 0.007*lije + 0.006*vasilia + 0.006*auroran + 0.005*chairman + 0.005*seldon',
 '0.029*gladia + 0.017*giskard + 0.013*amadiro + 0.008*solaria + 0.007*madam + 0.007*odeen + 0.007*vasilia + 0.007*gremionis + 0.006*jander + 0.006*dua',
 '0.029*giskard + 0.026*gladia + 0.016*solaria + 0.013*amadiro + 0.010*g + 0.010*madam + 0.007*solarian + 0.007*auroran + 0.006*vasilia + 0.006*settler',
 '0.024*gladia + 0.022*giskard + 0.015*amadiro + 0.010*jander + 0.009*chairman + 0.008*madam + 0.008*vasilia + 0.008*auroran + 0.007*solaria + 0.007*odeen',
 '0.029*gladia + 0.021*giskard + 0.016*amadiro + 0.015*odeen + 0.012*tritt + 0.011*dua + 0.009*g + 0.008*madam + 0.007*solaria + 0.007*vasilia']

**Comment by tmylk** [comment]
Hi Vadim,

There might be more people on [the Gensim mailing list](https://groups.google.com/forum/#!forum/gensim) who could answer this kind of question.
