### ISSUE TITLE
Anaconda Support for python 3.5.0

### ISSUE THREAD

**Issue by Aerylia** [piskvorky/gensim#510]
Hey,

I tried to install gensim with python 3.5.0, but got the flowing error:
Error: Unsatisfiable package specifications.
Generating hint: 

Hint: the following packages conflict with each other:
  - gensim
  - python 3.5*

Use 'conda info gensim' etc. to see the dependencies for each package.

Note that the following features are enabled:
  - vc14

I use pycharm 5.0 on windows 8 and installed used Anacoda3 2.4.0 to get python3.5.0 and all necessary packages and more.

Please look into this.

**Comment by piskvorky** [comment]
@tmylk is this gensim-related or anaconda-related? I can't see no reason why py3.5 should not work.

**Comment by tmylk** [comment]
This is an Anaconda problem. They (don't support)[http://docs.continuum.io/anaconda/pkg-docs] gensim for 3.5.

gensim without anaconda runs ok on Python 3.5 in our Linux, OSX and Windows build (environment)[https://ci.appveyor.com/project/tmylk/gensim-ahs80/build/job/iql4yxthxbcm83wg]

As there is vc14 - assume you are on Windows. Is that correct?

**Comment by gojomo** [comment]
As a workaround, does `pip install gensim` (while the conda environment is active) work? 

(Even when the conda system has had an older gensim, that's worked for me, to get the latest.)

**Comment by piskvorky** [comment]
Alright, thanks, closing the issue.

@Aerylia : either use `pip` like Gordon says, or wait for Anaconda to fix their distribution.
