### ISSUE TITLE
deepir notebook should do bayes norm on entire doc not every sentences

### ISSUE THREAD

**Issue by udibr** [piskvorky/gensim#514]
the same star value apply to all sentences in the same document and therefore the normalization
should be performed after summing up lhd on all sentences. this should be somehow countered with the fact that the number of sentences in each document is different, so I dont have a complete solution

    # normalize across models (stars) to get sentence-star probabilities
    prob = pd.DataFrame( (lhd/lhd.sum(axis=0)).transpose() )

**Comment by piskvorky** [comment]
Hi @udibr -- is this a bug report, or feature suggestion, or a comment, future PR announcement? Can you make the description a bit clearer?

CC @mataddy

**Comment by mataddy** [comment]
good eye.  actually, it depends on whether you assume each sentence has the same sentiment (stars here) when predicting.  in the notebook we don't, and the doc prob is then the average of sentence probs.  this works much better in my experience than the scheme I think you have in mind, where every sentence is forced to have the sentiment

**Comment by udibr** [comment]
Agrre. I think my only suggestion is to add this explanation to the notebook above the relevant cell.
(see this issue will be reporting missing comment/documentation.)

**Comment by piskvorky** [comment]
Great :) Can you add that in a pull request @udibr ?
