### ISSUE TITLE
ZeroDivisionError in Doc2Vec.build_vocab

### ISSUE THREAD

**Issue by jgc128** [piskvorky/gensim#518]
When I call `model.build_vocab(docs_iterator)` sometimes I got `ZeroDivisionError`:
```
Traceback (most recent call last):
  File "patient_notes_doc2vec.py", line 45, in <module>
    model.build_vocab(docs_iterator)
  File "/data2/aromanov/virt_env/theano/lib/python3.4/site-packages/gensim/models/word2vec.py", line 495, in build_vocab
    self.scan_vocab(sentences, trim_rule=trim_rule)  # initial survey
  File "/data2/aromanov/virt_env/theano/lib/python3.4/site-packages/gensim/models/doc2vec.py", line 634, in scan_vocab
    interval_rate = (total_words - interval_count) / (default_timer() - interval_start)
ZeroDivisionError: float division by zero
```

A few lines above in doc2vec.py `interval_start` is defined as `interval_start = default_timer()` and in the for loop we have
```
interval_rate = (total_words - interval_count) / (default_timer() - interval_start)
```

Perhaps my system is too fast :smiley:

**Comment by gojomo** [comment]
Too fast... or the clock too coarse! 

This definitely shouldn't happen; I'll likely add a +0.001 (or similar). Then the rate-estimate may occasionally be off, but the code won't error. 

Thanks for the report!

**Comment by gojomo** [comment]
Also reported by @kikohs in #529.

**Comment by tmylk** [comment]
@gojomo Pinging this issue. Is it an easy fix that can be include in this month's release?
