### ISSUE TITLE
Getting the error while importing gensim

### ISSUE THREAD

**Issue by Balachandhar777** [piskvorky/gensim#530]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/gensim/__init__.py", line 6, in <module>
    from gensim import parsing, matutils, interfaces, corpora, models, similarities, summarization
  File "/Library/Python/2.7/site-packages/gensim/models/__init__.py", line 13, in <module>
    from .word2vec import Word2Vec
  File "/Library/Python/2.7/site-packages/gensim/models/word2vec.py", line 100, in <module>
    from gensim.models.word2vec_inner import train_sentence_sg, train_sentence_cbow, FAST_VERSION,\
  File "__init__.pxd", line 155, in init gensim.models.word2vec_inner (./gensim/models/word2vec_inner.c:9234)
ValueError: numpy.dtype has the wrong size, try recompiling

**Comment by piskvorky** [comment]
Is it possible you reinstalled numpy, since installing gensim? How did you install these two?

In any case, it's probably easiest to do as the error says -- recompile (= re-install) gensim.

**Comment by Balachandhar777** [comment]
Hi,

I reinstalled genesis and numpy....But I am getting the same error.

I have MAC  system, so installed the Numpy using below commands,

>>sudo -H pip install numpy

Please help me with this.

**Comment by Balachandhar777** [comment]
Hi, Any update on the above problem?

**Comment by piskvorky** [comment]
What error do you get when you launch a new Python shell and type `from gensim import utils`?

**Comment by Balachandhar777** [comment]
When I try to import for the first time, I am getting the below error,

Traceback (most recent call last):
File "", line 1, in 
File "/Library/Python/2.7/site-packages/gensim/init.py", line 6, in 
from gensim import parsing, matutils, interfaces, corpora, models, similarities, summarization
File "/Library/Python/2.7/site-packages/gensim/models/init.py", line 13, in 
from .word2vec import Word2Vec
File "/Library/Python/2.7/site-packages/gensim/models/word2vec.py", line 100, in 
from gensim.models.word2vec_inner import train_sentence_sg, train_sentence_cbow, FAST_VERSION,\
File "init.pxd", line 155, in init gensim.models.word2vec_inner (./gensim/models/word2vec_inner.c:9234)
ValueError: numpy.dtype has the wrong size, try recompiling


When I try to import second time, I am getting a different error,

Traceback (most recent call last):
File "", line 1, in 
File "/Library/Python/2.7/site-packages/gensim/init.py", line 6, in 
from gensim import parsing, matutils, interfaces, corpora, models, similarities, summarization
File "/Library/Python/2.7/site-packages/gensim/models/init.py", line 13, in 
from .word2vec import Word2Vec
File "/Library/Python/2.7/site-packages/gensim/models/word2vec.py", line 92, in 
from gensim import utils, matutils # utility fnc for pickling, common scipy operations etc
ImportError: cannot import name utils

**Comment by piskvorky** [comment]
Same thing. It looks like gensim was compiled against a different version of numpy that the one you're actually using at runtime.

I saw you're using `sudo` to install packages. The easiest and safest fix would be to install `virtualenv` (plus `virtualenvwrapper` for convenience) and start having separate environments.

That way, you will avoid issues with different Python installations, sudo, different version etc.

**Comment by Balachandhar777** [comment]
ok Thanks a lot. I will do a try and update you...

**Comment by Balachandhar777** [comment]
Its working now....Thanks a lot....

**Comment by piskvorky** [comment]
Can you describe your final fix, for other people who may find this issue in the future?

**Comment by Balachandhar777** [comment]
This issue is all about having two versions of other packages and stuffs in python installation folder. So, gensim package is getting confused while referring to other needful packages. 

Solution to this problem : Create a virtual environment of python in your own system. (Like, you can run some projects with your base installation of python, While this virtual environment can be used for running other projects.(In my case, I am going to run all the projects which needs gensim package in virtual environment.)

How to create virtual environment in your system?
http://docs.python-guide.org/en/latest/dev/virtualenvs/

Follow this link and create a virtual environment of python.

How to switch between two different python environments?

To work on virtual environment:
$ source venv/bin/activate 

$ deactivate
To work on base version of python.

Hope this helps!!!!!!

**Comment by piskvorky** [comment]
Thanks @Balachandhar777 :)

**Comment by hayj** [comment]
I finally solve the problem without using a virtual env, try something like this :

```
sudo easy_install -U gensim
sudo apt-get install python-setuptools python-dev build-essential
sudo easy_install pip 
sudo apt-get remove python-numpy
sudo apt-get install python python-dev libatlas-base-dev gcc gfortran g++
sudo pip uninstall numpy
sudo pip install numpy
sudo pip install scipy
```

**Comment by piskvorky** [comment]
Let me just add that the `sudo` dance above is **highly unrecommended** (in case you googled up this thread in the future).

**Comment by Diyago** [comment]
What about solution on windows?

**Comment by misguju** [comment]
please if there is other solution for window users for importError "cannot import name corpora"

**Comment by piskvorky** [comment]
@tmylk is this a problem with anaconda again?

We'll have to detect this explicitly and give users more concrete warning & fix instructions, it keeps coming up.

**Comment by misguju** [comment]
@Balachandhar777 when  I type "source venv/bin/activate" command it this error  'source' is not recognized as an internal or external command, operable program or batch file. solution????
under which directory should I type the command?

**Comment by midnightradio** [comment]
@misguju The command mentioned by Balachandhar777 for activating virtualenv or '.' you probably meet by googling for the same functionality only works on Unix shell environment but you are playing with Windows. Better to find Windows way with activating virtualenv, I'm not sure if there's any though. I would rather focus on finding root cause of the problem than trying if virtualenv solves it.

**Comment by tmylk** [comment]
@misguju could you tell us more about the issue?  are you using anaconda? What is the error message that you are getting? Have you tried a virtual environment instead of anaconda?

**Comment by misguju** [comment]
@tmylk Yes I'm using anaconda specifically Jupyter Notebook. the error I got is importError "cannot import name similarity. I did not tried  virtual environment

**Comment by misguju** [comment]
@tmylk now it is ok with anaconda specifically Jupyter Notebook. sorry it has no problem but I imported similarity instead of similarities. that is spelling error

**Comment by harrypotter0** [comment]
Hi guys, I am facing this issue 
`import gensim from gensim                     ^
SyntaxError: invalid syntax
`
I am using Jupyter notebook with Python3 kernel for this and have tried above-mentioned methods. Please, can someone help. Thanks in advance.

**Comment by menshikh-iv** [comment]
hi @harrypotter0, that's really `SytaxError`, `from` shouldn't be after `import`, should be like `from gensim.models import Word2Vec`

**Comment by puramchendrasekhar1** [comment]
Hi guys !, I am getting same error while importing gensim , I have tried all  the methods which mentioned above , please help me ,Thanks in advance,

My code is 
import gensim
i=0
list_of_sent=[]
for sent in sampled_data['CleanedText'].values:
    filtered_sentence=[]
    sent=cleanhtml(sent)
    for w in sent.split():
        for cleaned_words in cleanpunc(w).split():
            if(cleaned_words.isalpha()):    
                filtered_sentence.append(cleaned_words.lower())
            else:
                continue 
    list_of_sent.append(filtered_sentence)
    
Error I am getting is 

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-047aec4c09a5> in <module>()
      1 # desigining our own word2vec by using sampled 2000 reviews (positive and Negative)
      2 import nltk
----> 3 import gensim
      4 i=0
      5 list_of_sent=[]

ModuleNotFoundError: No module named 'gensim'

I have installed gensim packages also still getting error, restarted my note book and system both.

**Comment by CoderTypist** [comment]
I had problems with ```import gensim``` while using Jupyter Notebook and Anaconda. People above had mentioned reinstalling numpy, so I ran ```conda update numpy```, restarted jupyter notebook, and the error was gone.
