### ISSUE TITLE
Setting the seed to Word2vec does not prevent randomness from results

### ISSUE THREAD

**Issue by arranger1044** [piskvorky/gensim#546]
I'd like to have the embedding learned by `Word2Vec` to be reproducible among runs by fixing the seed parameter in the constructor `gensim.models.word2vec.Word2Vec`. It does not appear to be working for me, can anyone confirm the issue?

**Comment by gojomo** [comment]
Are you using a single thread? (`workers=1`?) Otherwise, there remains randomness introduced by OS thread scheduling: training doesn't happen in the exact same order.

**Comment by arranger1044** [comment]
I see. Indeed, I am using more than one thread and this explains it all. The classic variance/performance trade off.

**Comment by divineSix** [comment]
Despite having the seed parameter set and a single worker thread, I am still unable to reproduce the word embedding. I am running Python 3.6 on Ubuntu using PyCharm, and not able to reproduce results despite setting the PYTHONHASHSEED. Can anyone tell me if I am missing something?

**Comment by gojomo** [comment]
@divineSix You would need to show a code example demonstrating your problem to guess what's going wrong. (What did you set PYTHONHASHSEED to? Are the exact same steps being followed each run? etc.) Working through such an issue should be done on the project discussion list, <https://groups.google.com/forum/#!forum/gensim>, unless/until it's show to involve some bug or required feature deserving an issue here.

**Comment by bwindsor22** [comment]
Resurrecting this thread -- [ 15+ threads on this question ](https://www.google.com/search?q=gensim+set+seed&rlz=1C1GCEB_en&oq=gensim+set+seed&aqs=chrome..69i57j0i22i30j69i60l4.2575j0j7&sourceid=chrome&ie=UTF-8), and I'm also seeing the same as divineSix despite setting PYTHONHASHSEED.

A lot of threads mention os scheduling, though "parallel" does not have to mean "randomized": you can parallelize a map or reduce step and still end up with a deterministic order.

@gojomo would you happen to know the part of this code where the parallelism takes place? Any interest in a pull request/project to modify it?

**Comment by gojomo** [comment]
@bwindsor22 As with the prior report, you would need to show a code example demonstrating your problem to guess what's going wrong. (How exactly did you set PYTHONHASHSEED? Are the exact same steps being followed each run? etc.) Working through such an issue should also be done on the project discussion list, https://groups.google.com/forum/#!forum/gensim, unless/until it's shown to involve some bug or required feature deserving an issue here.

The use of parallel native threads absolutely puts the model under the influence of unpredictable OS-level thread scheduling changes, *unless* significant extra code were added, with associated complexity & thread-private-state & synchronization-overhead-delays, for threads to only merge their respective separate results in a wholly-deterministic way. 

But it is also my opinion that pursuing this level of determinism with inherently-randomized algorithms, and especially those were async parallelism offers a big speedup, is almost always a bad idea. (Multithreaded/multiprocess algorithms in `scikit-learn` have the same behavior.) The [Gensim FAQ questions 11 & 12](https://github.com/RaRe-Technologies/gensim/wiki/Recipes-&-FAQ#q11-ive-trained-my-word2vec--doc2vec--etc-model-repeatedly-using-the-exact-same-text-corpus-but-the-vectors-are-different-each-time-is-there-a-bug-or-have-i-made-a-mistake-2vec-training-non-determinism) cover some reasons why. 

For that reason, I'd not be interested in adding any new forced-determinism options. The current single-threaded option, which can be forced if someone is really insistent, seems enough to me.
