### ISSUE TITLE
Topics Probabilities do not sum up to 1

### ISSUE THREAD

**Issue by nouramoubayed** [piskvorky/gensim#561]
Could anyone please explain why the topics probabilities for some of text documents do not sum up to 1. 
I have been using Gensim in my research for one year now and everything seems great until I decided to construct pie-charts for the topic distribution for every text document i have (tens of thousands) and I noticed that the sum over topic probabilities for some of these documents is less than 1. the values vary from 0.5 to 1. is there any explanation or justification for this to happen?

many thanks

**Comment by piskvorky** [comment]
Answered on the gensim mailing, for example yesterday: 
https://groups.google.com/forum/#!topic/gensim/F4AWfh9yIhM
