### ISSUE TITLE
How to tune word2vec to my data

### ISSUE THREAD

**Issue by Sandy4321** [piskvorky/gensim#578]
If I need to tune existing word to vec to my corpus,  can  I ? Thanks

**Comment by phdowling** [comment]
You could probably just load a trained word2vec model and add more documents via online training (jsut use the `train` method).

How large is your corpus? Are you sure fine-tuning is the way to go?

**Comment by tmylk** [comment]
Closing as resolved. Such an open question is a good fit for the mailing list
https://groups.google.com/forum/#!forum/gensim
