### ISSUE TITLE
Example of saving Corpus, Model ans Similarity to Amazon S3?

### ISSUE THREAD

**Issue by nanounanue** [piskvorky/gensim#583]
I am trying to do it, but It makes an error already reviewed the closed issues, but it is not clear (for me at least) how to store them in S3 using pickle, could some one help me?

**Comment by tmylk** [comment]
HI @nanounanue , please consider smart_open package for easy S3 handling.
Also, an open question like this is best fit for the gensim mailing list
https://groups.google.com/forum/#!forum/gensim
