### ISSUE TITLE
gensim.parsing.stem_text does not work properly for some cases

### ISSUE THREAD

**Issue by hanabi1224** [piskvorky/gensim#597]
```
from gensim.parsing import stem_text
stem_text('keys')
>>> u'kei'
```

while nltk.stem.snowball.SnowballStemmer can give 'key'

**Comment by cscorley** [comment]
Indeed, the one in `gensim.parsing` is a Porter-based stemmer.  You should get the same result when using `nltk.stem.porter.PorterStemmer`.

**Comment by cscorley** [comment]
Hm, strange! `nltk.stem.porter.PorterStemmer` gives 'key' as well.

**Comment by piskvorky** [comment]
`kei` is the proper output for Porter stemmer.

There are probably many variants of Porter stemmer though, all called "Porter", so it wouldn't surprise me if some worked differently. The one in NLTK I'd expect to be more advanced than the one in `gensim.parsing`.

**Comment by piskvorky** [comment]
@hanabi1224 closing this now; let me know if you have other questions.

I'd recommend using a specialized NLP package for stemming (or even better, for lemmatization) of your inputs. `gensim.parsing` is a historical relict inside gensim, no longer actively developed or accepting new functionality.
