### ISSUE TITLE
Feature (word) weights from infer_vector in doc2vec 

### ISSUE THREAD

**Issue by tokestermw** [piskvorky/gensim#598]
I'm probably not completely understanding the math behind infer_vector so forgive my ignorance. But is there a way to extract the feature weights for words when predicting new paragraph vectors? I'd like to know which words are most important similar to what people do for feature selection / engineering ML models.

Thanks

**Comment by piskvorky** [comment]
Hello @tokestermw , please use the gensim mailing list for general user questions:
https://groups.google.com/forum/#!forum/gensim

We try to keep Github issues focused on dev issues, bugs and development coordination.
