### ISSUE TITLE
unable to access index_to_doctag in gensin doc2vec 

### ISSUE THREAD

**Issue by priyaradhakrishnan0** [piskvorky/gensim#602]
gensin doc2vec index_to_doctag AttributeError: 'DocvecsArray' object has no attribute 'index_to_doctag'

In creating the doc2vec model we have used utf-8 encoded string as tags. Accordingly the files doctag_syn0_lockf.np and doctag_syn0.npy were created. 
So doctags exist and we are able to access them with indexed_doctags.
But unable to access index_to_doctag
>>> from gensim.models.doc2vec import Doc2Vec
>>> model = Doc2Vec.load('wiki_model4.doc2vec')
>>> len(model.docvecs)
15081689
>>> model.docvecs.indexed_doctags(u'Category:State Basketball League teams')
([2291267, 17877, 10944564, 2181520], array([[-0.00459304, -0.0062908 , -0.00926408, ...,  0.03596618,
         0.01399021,  0.00461491],
       [-0.00727673,  0.04267709, -0.02805031, ...,  0.12569368,
         0.12545307,  0.00841415],
       [ 0.04587144, -0.05621753,  0.06287887, ...,  0.01862248,
        -0.00645287,  0.00781868],
       ..., 
       [ 0.00131883,  0.00148042, -0.00071769, ..., -0.00032956,
         0.00063222, -0.00111612],
       [ 0.00112057, -0.00082622, -0.00029666, ..., -0.00057247,
         0.00116911, -0.00140173],
       [ 0.0015768 , -0.00110063, -0.00022804, ..., -0.00142337,
        -0.00128761, -0.00034992]], dtype=float32), array([ 1.,  1.,  1., ...,  1.,  1.,  1.], dtype=float32), u'Category:State Basketball League teams')
>>> model.docvecs.indexed_doctags(u'Category:State Basketball League teams')[0]
[2291267, 17877, 10944564, 2181520]
>>> model.docvecs.index_to_doctag(221267)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'DocvecsArray' object has no attribute 'index_to_doctag'
>>> 
>>>

**Comment by gojomo** [comment]
The `index_to_doctag()` method only appeared in genim 0.12.3. Are you sure you're on that version or higher? 

Also, unless you're certain that a problem/question you're having is a bug, it's better to discuss it on the project forum – https://groups.google.com/forum/#!forum/gensim – than in the project issue tracker. So I'm closing this issue, and please follow up in the forum. (If this does turn out to be a bug, the issue can be re-opened.)

**Comment by nick-magnini** [comment]
@priyaradhakrishnan0 How did you train the 'wiki_model4.doc2vec' to have the categories included? Do you have a sample of your code somewhere? Also can you mention the statistics of how long did it take to train the whole model?

**Comment by priyaradhakrishnan0** [comment]
I have used the wiki english copus.
I extracted pages using

gensim.corpora.wikicorpus.extract_pages('enwiki-latest-pages-articles.xml')

I construct TaggedDocument with pageTitle and pageId as

for page in pages:

**Comment by priyaradhakrishnan0** [comment]
I have used the wiki english copus.
I extracted pages using

gensim.corpora.wikicorpus.extract_pages('enwiki-latest-pages-articles.xml')

I construct TaggedDocument with pageTitle and pageId as

for page in pages:
    yield TaggedDocument(page[1], page[0])
...
model = Doc2Vec( alpha=0.025, size=300, window=8, min_count=5, workers=0)
model.train(documents)
...

On a dual-core CPU with 4GB RAM, this took 12 hours.
-priya
