### ISSUE TITLE
Feature proposal: simple provenance management

### ISSUE THREAD

**Issue by shirish93** [piskvorky/gensim#603]
Hello,

Would a simple provenance management system to record the parameters a model was trained in, be aligned with the goals of gensim? 

For example, when the user trains Word2Vec/Doc2Vec (or other models), by calling the constructor for that model, the parameters used to train are made members of the model. When the model is saved, the parameters are saved in a human-readable (json?) format along with the other model files. Loading the model will make the original training information be accessible again.

It would be backwards-compatible in the sense that if there is no associated training information available when training, the fields related would be empty.

This would be quite useful for people like myself, who train a lot of models (on same data, and on different data), with different parameters. More recently, I manually keep track of model name/versions, and the parameters used in training. However, a few of my better-performing models have had their relevant information lost, so the models are now much  'dark magic' now.

Any ideas? I can put in a very simple pull request if anyone thinks this is an option worth exploring to get things rolling. Feel free to close the issue if it doesn't seem like something that gensim should have/ is already implemented that I missed.

**Comment by gojomo** [comment]
Can you give an example of particular details that aren't currently retained? (I'd agree as much as possible should be retained... and think most of it is, so addressing this is a matter of working through the exact checklist of what's missing.)

**Comment by shirish93** [comment]
Closing because it appears that every desired feature is retained. Apologies for the poor research that led to raising the issue.
