### ISSUE TITLE
How can I push to a new gensim branch?

### ISSUE THREAD

**Issue by jhlau** [piskvorky/gensim#604]
Hi, this isn't a gensim issue per se, but I've created a branch and made a few changes and I got a permission denied error when trying to push the new branch (git push origin branch_name). Do I have to register as a member to create a branch? Sorry I haven't had experience doing branching before so this might be a dumb question.

**Comment by piskvorky** [comment]
Hello @jhlau, the proper way to submit contributions on github is using [pull requests](https://help.github.com/articles/using-pull-requests/).

There are tons of tutorials on this online; let us know if you follow the standard pull request procedure and something doesn't work.

**Comment by jhlau** [comment]
Yeap. I realised I needed to fork the project first. All is good now. Many thanks.
