### ISSUE TITLE
can gensim identify causal relationships in sentence structure?

### ISSUE THREAD

**Issue by elevine89** [piskvorky/gensim#606]
Good morning,

I was wondering if Gensim has the ability to identify assumptions of causal relationships in sentence or paragraph structures (if x then y happens more)?  I'd like to see if it would be possible to automate Integrative Propositional Analysis to evaluate the complexity and interrelatedness of theories and documents.

Thank you so much!

**Comment by piskvorky** [comment]
Good evening!

Unfortunately not, that's out of gensim's scope.

If you want to ask the gensim community whether anyone has experience with such tasks, the best place is the [gensim mailing list](https://groups.google.com/d/forum/gensim).
