### ISSUE TITLE
Recommended way to deal with metadata

### ISSUE THREAD

**Issue by vspinu** [piskvorky/gensim#608]
Hi, 

I have some metadata (name, timestamp) for each document in my corpus. What's the most straightforward way to deal with that? 

I see that there is some provision for metadata in some models, but there is no documentation on that.

I would like to use MM format and to freeride on MmCorpus loading/serialization infrastructure if possible, but MmCorpus doesn't even have metadata field.

Thanks.

**Comment by cscorley** [comment]
How you handle metadata and corpus reading is up to you.  For example, `MalletCorpus` format features each document tagged with an identifier and origin language.  To re-use `MmCorpus`, you could inherit and extend the current class to also read from a secondary file containing the metadata for the original corpus file.

**Comment by vspinu** [comment]
Thanks. I have turned to MalletCorpus, but it's unbearrably slow for word2id computation and breaks with metadata. Opening a new issue for that.

**Comment by cscorley** [comment]
Yep, the slowness is expected with a list of words kind of format. I was pointing it out as an example for how metadata can be implemented for a custom corpus.
