### ISSUE TITLE
The parameter "minimum_probability" is not working, why?

### ISSUE THREAD

**Issue by wjwangjian** [piskvorky/gensim#613]
Os: Win7
Version: gensim 0.12.4
In ldamodel.py, the parameter "minimum_probability" of mothed "get_document_topics" is not working. anybody knows why?

**Comment by piskvorky** [comment]
What makes you think it's not working? Can you post a minimal failing example?

**Comment by wjwangjian** [comment]
@piskvorky i set the "minimum_probabilit" like this: result = lda.get_document_topics(corpus, minimum_probability=0.2)
but the result is not filtered

**Comment by piskvorky** [comment]
Looking at the code, I can't see how that can happen. Can you copy&paste a **concrete** example (exact call + exact response)?

**Comment by wjwangjian** [comment]
`lda = ldamodel.LdaModel.load("article.lda.model", mmap='r')
result = lda.get_document_topics(corpus)
print [x for x in result]`
The response:
`[[(56, 0.080024634219998697), (60, 0.073457164692094221), (100, 0.12326501754801131), (111, 0.07842169896383544), (116, 0.21309146918090843), (125, 0.17679339719187781), (199, 0.18071584896110657)]]`
When i set the "minimum_probability",like this:
`lda = ldamodel.LdaModel.load("article.lda.model", mmap='r')
result = lda.get_document_topics(corpus, minimum_probability=0.2)
print [x for x in result]`
But,the result is the same as before:
`[[(56, 0.080060512577497897), (60, 0.073303371567709899), (100, 0.12265701147900646), (111, 0.078429510466424837), (116, 0.21248663560591044), (125, 0.1751707412661721), (199, 0.18366144779499866)]]`

**Comment by piskvorky** [comment]
Thanks. That is bizarre indeed.

@cscorley any idea how that could be?

**Comment by piskvorky** [comment]
Oh, I think I see the problem. You're passing a corpus (not single document), and the argument of `minimum_probability` is not passed along to `return self._apply(corpus)`.

I'd say this is a bug. You're simplest way to fix is to set `lda.minimum_probability = 0.2` (rather than pass it as parameter. But we should aim to fix the "parameter to corpus" as well @tmylk .

**Comment by wjwangjian** [comment]
@piskvorky  anyway ， thanks！

**Comment by likerainsun** [comment]
I have the same problem

 File "/home/ssd/workspace/modReviews.v.2.0/src/extract_infotype_feature.py", line 65, in extract_lda_vec_crf
    txt_lda = self.lda[txt]
  File "/usr/local/lib/python2.7/dist-packages/gensim-0.12.3-py2.7-linux-x86_64.egg/gensim/models/ldamodel.py", line 890, in __getitem__
    return self.get_document_topics(bow, eps)
  File "/usr/local/lib/python2.7/dist-packages/gensim-0.12.3-py2.7-linux-x86_64.egg/gensim/models/ldamodel.py", line 870, in get_document_topics
    minimum_probability = self.minimum_probability
AttributeError: 'LdaModel' object has no attribute 'minimum_probability'


I found it is related with the gensim version.
When I train the lda model with a lower version of gensim and use it with the newest version of gensim, it happens. Anyidea?

**Comment by wjwangjian** [comment]
Sorry,i can't see what happened exactly,Can you copy exact call + exact response?

**Comment by piskvorky** [comment]
Yes, old versions of gensim didn't have that attribute. Use the trained model in the same gensim version as it was trained in.
