### ISSUE TITLE
CalledProcessError

### ISSUE THREAD

**Issue by aleissaf** [piskvorky/gensim#621]
I have been trying to use the wrapper as follows:

```python
model = gensim.models.wrappers.LdaMallet(
    '/Users/f/Downloads/mallet-2.0.7/bin/mallet',
    corpus, num_topics=10, id2word=dictionary)
```

And I keep getting an error

*CalledProcessError: Command '/Users/f/Downloads/mallet-2.0.7/bin/mallet import-file --preserve-case --keep-sequence --remove-stopwords --token-regex '\S+' --input /var/folders/ml/xbzdgxlj3hv5j358pj82ktr80000gn/T/10cc8c_corpus.txt --output /var/folders/ml/xbzdgxlj3hv5j358pj82ktr80000gn/T/10cc8c_corpus.mallet' returned non-zero exit status 2*

**Comment by piskvorky** [comment]
What does the log say?

What do you see when you run the same command from CLI yourself (without gensim or Python)?

**Comment by aleissaf** [comment]
sage: dirname path
usage: dirname path
Error: Could not find or load main class cc.mallet.classify.tui.Csv2Vectors

**Comment by piskvorky** [comment]
No idea what "Csv2Vectors" is. This is the result when you run Mallet from command line, without any Python?

**Comment by aleissaf** [comment]
That is what I get when I run this command
/Users/f/Downloads/mallet-2.0.7/bin/mallet import-file --preserve-case --keep-sequence --remove-stopwords --token-regex '\S+' --input /var/folders/ml/xbzdgxlj3hv5j358pj82ktr80000gn/T/10cc8c_corpus.txt --output /var/folders/ml/xbzdgxlj3hv5j358pj82ktr80000gn/T/10cc8c_corpus.mallet

**Comment by piskvorky** [comment]
OK. Probably best to ask at the Mallet mailing list, as this is clearly not related to gensim (happens with plain Java too).

It could be some Java classpath problem or similar.

**Comment by tmylk** [comment]
@aleissaf Did you find a resolution to this problem on the Mallet mailing list? Would appreciate a fix to share with other users.

**Comment by tmylk** [comment]
Closing as abandoned.
