### ISSUE TITLE
Unexpected pruning in Word2Vec

### ISSUE THREAD

**Issue by hwsamuel** [piskvorky/gensim#626]
The Word2Vec model seems to be unexpectedly pruning some indexes. For reproducing, please see the function below:

```python
from gensim.models import word2vec

def bigram2vec(unigrams, bigram_to_search):
    bigrams = Phrases(unigrams)
    model = word2vec.Word2Vec(sentences=bigrams[unigrams], size=20, min_count=1, window=4, sg=1, hs=1, negative=0, trim_rule=None)
    if bigram_to_search in model.vocab.keys():
        return model[bigram_to_search]
    else:
        return None
```

The pruning is unexpected because I have set `min_count = 1` and also set `trim_rule = None`. The assertion for pruning can be checked via `len(model.vocab.keys()) != len(bigrams.vocab.keys())`. If my dataset is needed to reproduce this issue, I might be able to provide that.

**Comment by gojomo** [comment]
I've commented on the list: https://groups.google.com/d/msg/gensim/lsDU42VksJA/ZasFdb21HAAJ

I don't think there's any bug here, so closing this issue.

**Comment by hwsamuel** [comment]
Thanks for that, for future reference, the corrected solution code is below.

```python
from gensim.models import word2vec

def bigram2vec(unigrams, bigram_to_search):
    bigrams = Phrases(unigrams,min_count=1,threshold=0.1)
    model = word2vec.Word2Vec(sentences=bigrams[unigrams], size=20, min_count=1, trim_rule=None)
    if bigram_to_search in model.vocab.keys():
        return model[bigram_to_search]
    else:
        return None
```
