### ISSUE TITLE
Pre-computing L2-norm vectors forgetting the original ones in Doc2Vec no longer allows inference

### ISSUE THREAD

**Issue by daniel-j-h** [piskvorky/gensim#640]
The documentation for [`init_sims(replace=True)`](http://radimrehurek.com/gensim/models/doc2vec.html#gensim.models.doc2vec.Doc2Vec.init_sims
) states:

> Note that you cannot continue training after doing a replace. The model becomes effectively read-only = you can call most_similar, similarity etc., but not train.

After dropping the original vectors, we're not only no longer able to `train()`, but we can also no longer infer by means of [`infer_vector()`](http://radimrehurek.com/gensim/models/doc2vec.html#gensim.models.doc2vec.Doc2Vec.infer_vector
) (I learned this the hard way).

I understand the case for this after reading the Paragraph Vectors paper:

> At prediction time, the paragraph vectors are inferred by fix-ing the word vectors and training the new paragraph vector until convergence.

and

> In summary, the algorithm itself has two key stages: 1) training to get word vectors W , softmax weights U, b and paragraph vectors D on already seen paragraphs; and 2) “the inference stage” to get paragraph vectors D for new paragraphs (never seen before) by adding more columns in D and gradient descending on D while holding W, U, b fixed.

Reference: http://cs.stanford.edu/%7Equocle/paragraph_vector.pdf

It would be great to have a note about this in the documentation.

**Comment by gojomo** [comment]
@daniel-j-h – Please suggest as a PR the note that would have been most helpful to you!

**Comment by gojomo** [comment]
I was touching up other doc-comments, and added a few words to this effect in the `Doc2Vec.infer_vector()` comment in #642.

**Comment by daniel-j-h** [comment]
Perfect, this hopefully clarifies things!

For the record, I found gensim a pleasure to work with _as long_ as one takes the time to read tutorials and 3rd party examples on it. In my case (using Doc2Vec) first reading Word2Vec docs, tutorials and examples, then the same for Doc2Vec and even reading the Paragraph Vectors paper made the interface clearer to me. For a complete beginner in this area, a few words more in the docs here and there could certainly be helpful.

**Comment by tmylk** [comment]
Closing as resolved.

**Comment by piskvorky** [comment]
Yes @daniel-j-h , we definitely need better docs, tutorials and examples all around (not just doc2vec).

The current phrasing too often targets gensim-experts and I'm not happy about that (contradicts the "for humans" tagline).

**Comment by tmylk** [comment]
@daniel-j-h Thanks a lot for describing your path to understanding the package.
We plan to spend all of our summer conference sprints writing docs at [SciPy](http://scipy2016.scipy.org/ehome/146062/332969/?&&) and [PyCon](https://us.pycon.org/2016/community/sprints/) and your feedback will help us to structure them.

**Comment by daniel-j-h** [comment]
It's nice to see such a positive response! Keep up the good work! If it is of any help, this is my side project I did over the Easter weekend using gensim (and NLTK) for the first time: https://github.com/daniel-j-h/classyshoes
