### ISSUE TITLE
Intel MKL FATAL ERROR: Cannot load libmkl_avx.so or libmkl_def.so.

### ISSUE THREAD

**Issue by nipunsadvilkar** [piskvorky/gensim#652]
When I install **Gensim** using local python (/usr/local/bin/python2.7) it doesn't raise any errors. It installed smoothly and even when I import it doesn't raise any error.

`$ sudo pip install gensim`

Importing in local python : 
```
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gensim
>>> 
```

 But,
 when I install using Anaconda python (/anaconda2/bin/python)

`root@localhost:/home/Downloads/gensim-0.12.4# python setup.py test`

Here, **python** is Anaconda python interpreter and not local machine python interpreter.
  
This test raises following error:

`Intel MKL FATAL ERROR: Cannot load libmkl_avx.so or libmkl_def.so.`

even with `conda install gensim`

It installs Gensim but Importing in Anacoda python environment rasies same above error and crashes Anaconda python interpreter: 

```
Python 2.7.11 |Anaconda 4.0.0 (64-bit)| (default, Dec  6 2015, 18:08:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import gensim
Intel MKL FATAL ERROR: Cannot load libmkl_avx.so or libmkl_def.so.
root@localhost:/home/Downloads/gensim-0.12.4#
```

Anyone know what's the solution?

**Comment by piskvorky** [comment]
Solution is to report this at Anaconda, as suggested on the [mailing list](https://groups.google.com/forum/#!topic/gensim/PAqtRG6nL5w).
