### ISSUE TITLE
Potential bug in word2vec.py score_sg_pair and score_cbow_pair

### ISSUE THREAD

**Issue by brooksjd** [piskvorky/gensim#653]
Hello,

I think there is a bug in word2vec.py in score_sg_pair and score_cbow_pair. Both functions run the line 
`sgn = -1.0**word.code  # ch function, 0-> 1, 1 -> -1`

with the intention of converting the word's huffman encoding from an array of 0s and 1s to an array of 1s and -1s. However when I tested this line of code, the negation in the -1.0 happens after the exponentiation, so it actually converts the codes into an array entirely consisting of -1s.

word2vec_inner.pyx has a set of parens around the -1, so I don't think the c-version of the training code is affected by this.

**Comment by gojomo** [comment]
attn: @mataddy

**Comment by mataddy** [comment]
@gojomo @brooksjd thanks!  that is indeed a bug, good catch.  @brooksjd can you add the parentheses and put in a PR?

**Comment by brooksjd** [comment]
Yeah no problem, added.

**Comment by mataddy** [comment]
awesome, thanks @brooksjd
