### ISSUE TITLE
Per-document topic probabilities not summing to 1?

### ISSUE THREAD

**Issue by ziyuang** [piskvorky/gensim#660]
gensim version: 0.12.4
I have a corpus and a LDA topic model trained from the corpus after tf-idf transform (downloaded [here][1]). To get the (sparse) document-topic matrix:

    from gensim import corpora, models
    from gensim.matutils import corpus2dense
    import numpy as np
    
    corpus = corpora.MmCorpus('corpus.mm')
    corpus_tfidf = models.TfidfModel(corpus)[corpus]
    lda = models.LdaModel.load('lda.model')
    d2t=lda[corpus_tfidf]

And to check the sum of probabilities in `d2t`'s first document:

    np.random.seed(0)
    sum([tup[1] for tup in d2t[0]])  # gives 0.89328769208986158

I expected the sum of the topic probabilities would be 1. Did I miss something?

  [1]: https://dl.dropboxusercontent.com/u/1335302/lda.7z

**Comment by piskvorky** [comment]
Thanks for the detailed report. See #561 for explanation.

Closing as duplicate.
