### ISSUE TITLE
word2vec gensim multi core training

### ISSUE THREAD

**Issue by srikar2097** [piskvorky/gensim#668]
@piskvorky before stating my issue I wish to express my deep gratitude for creating this awesome port of word2vec. Humbled by the effort & depth in thinking (extends to tomas et al). 

Coming to the issue, from the code & from other forum posts I gather that `model.build_vocab` is a single core but `model.train` should run on multiple cores. But on my 32-core EC2 instance it only takes 1 core in training 2B+ words dataset. I have attached screenshot of `top` & training output. I am unsure where else to look. Can you please help?

Look at pid 31696 which is the one undergoing training
<img width="641" alt="pid_31696_top_showing_1core_getting_used" src="https://cloud.githubusercontent.com/assets/391500/14579036/5cfbf26a-03b9-11e6-9f85-367d3a9d2e2a.png">

training output from word2vec logger
<img width="846" alt="training_phase" src="https://cloud.githubusercontent.com/assets/391500/14579037/6cb09012-03b9-11e6-96f7-aff04a1653fc.png">

My code - 
```
def train_model(path, do_stem):
    sentences = MySentences(local_path, stem_line=do_stem) #sentence iterator
    model       = word2vec.Word2Vec(workers=32, size=300, min_count=20, window=10, sample=1e-3)
    logger.info('Created dummy word2vec model instance')

    #building vocabulary, saving after vocabulary is built - this run on 1CORE
    model.build_vocab(sentences)
    vocab_name = '%s_word2vec.vocab' % u.rand_eng_word(words=1)
    try: model.save(vocab_name)
    except: logger.info('ERROR: Unable to save '+vocab_name)
    logger.info('Vocabulary built')

    #training model - why is this running on 1CORE ???
    #model.train(sentences, queue_factor=32)
    model.train(sentences)
    logger.info('Training neural network done')
    model_name = '%s_word2vec.bin' % u.rand_eng_word(words=1)
    model.save(model_name)
    logger.info('Model Trained & saved as '+model_name)
    return
```
System Specifications -
1. 32 core
2. 60GB RAM
3. 600GB SSD hard disk - Sentence iterator should not cause I/O bottleneck. SSD's are almost as fast as RAM.
4. running RedHat Linux Amazon EC2 instance

Below are my configurations -
```
gensim version = '0.12.4'

scipy version = '0.17.0'

numpy version = '1.11.0'

gensim.models.word2vec.FAST_VERSION = 1

scipy.show_config() 

atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_threads_info:
    libraries = ['lapack', 'ptf77blas', 'ptcblas', 'atlas']
    library_dirs = ['/usr/lib64/atlas']
    define_macros = [('NO_ATLAS_INFO', -1)]
    language = f77
    include_dirs = ['/usr/include']
blas_opt_info:
    libraries = ['ptf77blas', 'ptcblas', 'atlas']
    library_dirs = ['/usr/lib64/atlas']
    define_macros = [('HAVE_CBLAS', None), ('NO_ATLAS_INFO', -1)]
    language = c
    include_dirs = ['/usr/include']
openblas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
    libraries = ['ptf77blas', 'ptcblas', 'atlas']
    library_dirs = ['/usr/lib64/atlas']
    define_macros = [('HAVE_CBLAS', None), ('NO_ATLAS_INFO', -1)]
    language = c
    include_dirs = ['/usr/include']
lapack_opt_info:
    libraries = ['lapack', 'ptf77blas', 'ptcblas', 'atlas']
    library_dirs = ['/usr/lib64/atlas']
    define_macros = [('NO_ATLAS_INFO', -1)]
    language = f77
    include_dirs = ['/usr/include']
openblas_lapack_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
mkl_info:
  NOT AVAILABLE
```

**Comment by piskvorky** [comment]
My guess is you're running the non-optimized Python word2vec.

What does `print gensim.models.word2vec.FAST_VERSION` say?

**Comment by srikar2097** [comment]
@piskvorky I have put that above. FAST_VERSION =1. gensim.models.word2vec.FAST_VERSION = 1
I have installed cython. 
```
>>> import cython
>>> cython.__version__
'0.24'
```
another behavior, when I load all sentences into RAM, & init word2vec like so. All cores are at work.
`model = word2vec.Word2Vec(cleaned_data, workers=u.ncores(), size=300, min_count=20, window=10, sample=1e-3)`

But when I start streaming data & feet it, it only uses 1 core.

**Comment by piskvorky** [comment]
You don't need cython for gensim. `FAST_VERSION==1` should be fine.

Maybe your sentence iterator is too slow? What is the streaming speed, just going over the sentences, without any word2vec?

**Comment by srikar2097** [comment]
@piskvorky  Thanks again for taking time to reply. 

What I don't get is, having specified workers = 32, shouldn't gensim spawn 32 processes (via multiprocessing)? Then these 32 would start reading off Sentence iterator which then could potentially cause I/O bottleneck.

In my case, only 1 process is reading off Sentence iterator, Why only 1 process? In this case should I/O speed matter? Why are there no 32 workers spawned by gensim word2vec?

Btw, this EC2 instance has a 500GB SSD & I have put these huge files on local disk to have high streaming speed. My guess is I/O should not be a problem.

**Comment by piskvorky** [comment]
Word2vec uses multiple threads, not multiple processes. One thread is dedicated to reading your input iterator; see [parallelizing word2vec in gensim](http://rare-technologies.com/parallelizing-word2vec-in-python/).

Can you measure how long the plain iterator pass takes, just to be sure?

@gojomo , can you think of any reason why the same corpus should parallelize differently with `corpus_iterator` vs `list(corpus_iterator)`?

**Comment by srikar2097** [comment]
@piskvorky I do little bit of pre-processing on each sentence. lowercase, remove special chars etc. Here are the benchmarks for sample of **625K** sentences -

Benchmark code
```
start = timer()
for line in open(''625k_sample.txt"):
    #clean_data(line) #preprocessing step
    pass
end = timer()
print(end - start)
```
No Preprocessing = 0m1.260s
With preprocessing (clean_data uncommented) = 28m4.144s

With no Preprocessing we see that it just takes 1.2 seconds to run through 625K sentences. With preprocessing it takes 29m. Either way this proves there is no I/O bottleneck. If anything, it takes 29 minutes with preprocessing as its running only on 1 thread. With 32 threads it probably would have taken about 1 minute (28m/32).

**Comment by piskvorky** [comment]
It looks like your input sentence iterator is the bottleneck then. It's too slow to feed the word2vec threads.

I'd suggest speeding up your corpus preprocessing code. Or perhaps storing the already-preprocessed corpus and using that, if possible.

I think this explains the discrepancy between `list(sentences)` and `sentences`, so I'm closing this. Let me know if you have other questions!

**Comment by ahmedahmedov** [comment]
I am having the exact same issue. To make things worse, in my case, it takes 3 days for the build_vocabulary phase to be completed.

**Comment by gojomo** [comment]
@ahmedahmedov Of course it's *possible*! But it's not dirt-simple, and would generally put more constraints on the source data format than the simple single-iterator approach. And the overhead involved with combining counts from multiple threads can be a bit tricky to deal with. Still, it's a wishlist item – see #400 – that someone might do eventually. 

If your data source is especially appropriate to handle in parallel – such as a single uncompressed file, or many equal-sized shards, or similar – you could always reimplement the `scan_vocab()` step within `build_vocab()`, simply ensuring your end-state is the same as the next steps expect. And if your approach seems generalizable for others, you could contribute it back to gensim. 

(If your 3-day elapsed time isn't strictly due to a giant dataset, but some other bottleneck, moving to an SSD or ensuring that no swapping occurs at any point during the process might help, or preprocessing to eliminate excess tokens of little interest.)

**Comment by tvrbanec** [comment]
I have the same issue. 4 cores, and word2vec fast version use only 1. SSD, text is preprocessed, everything is in RAM, so there is no visible bottleneck.
