### ISSUE TITLE
Default of `initialize_lda` is false in DTM wrapper, usually leading to an exit error.

### ISSUE THREAD

**Issue by bhargavvader** [piskvorky/gensim#674]
The default value of `initialize_lda` is `false` in the DTM wrapper, which means that it assumes an `initial-lda-ss.dat` exists in the output folder, but this usually does not exist - especially because the output folder is being created on the fly in `/tmp` by the wrapper code. When run without `initialize_lda` being set as `True`, it throws  `CalledProcessError` and  `returned non-zero exit status 1`, because of this error  - `Error opening file output_folder/initial-lda-ss.dat`

Even in the [sample command line example ](https://github.com/blei-lab/dtm/blob/master/dtm/sample.sh)given in the original Blei dtm code, `initialize_lda` is set as `True`,  and is false only if one LDA run had already happened. In the Gensim [tutorial](https://github.com/piskvorky/gensim/blob/756524c189c4a25ac846afbb02c884cd3098020c/docs/notebooks/dtm_example.ipynb), the model has `initialize_lda` explicitly passed as `True`. 

Wouldn't it be easier for the model to set the variable as True on it's own so as to avoid the inevitable error when the user runs it without it being set? 

I might be missing out on something for the reason it is set as `False`. though - I am not 100% sure of the practices in initializing parameters, or if there is any other reason for this.

**Comment by tmylk** [comment]
Agree. Please submit PR changing default to True and will merge.

**Comment by bhargavvader** [comment]
Yeah, will do.

**Comment by bhargavvader** [comment]
@tmylk , closing this issue since PR has been merged.
