### ISSUE TITLE
'Doc2Vec' object has no attribute 'corpus_count'

### ISSUE THREAD

**Issue by silentsnooc** [piskvorky/gensim#680]
Line 685 of word2vec.py throws 
```
Traceback (most recent call last):
  File "/opt/pycharm/pycharm-edu-2.0.3/helpers/pydev/pydevd.py", line 2407, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/opt/pycharm/pycharm-edu-2.0.3/helpers/pydev/pydevd.py", line 1798, in run
    launch(file, globals, locals)  # execute the script
  File "/home/sfalk/PycharmProjects/wordvectors/doc2vec.py", line 41, in <module>
    model.train(labeled_line_sentence)
  File "/usr/local/lib/python2.7/dist-packages/gensim/models/word2vec.py", line 685, in train
    if self.corpus_count:
AttributeError: 'Doc2Vec' object has no attribute 'corpus_count'
```

The code I used:

```python
import json
from gensim.models.doc2vec import TaggedDocument, Doc2Vec

class LabeledLineSentence(object):

    def __init__(self, filename):
        self.filename = filename

    def __iter__(self):
        for uid, line in enumerate(open(self.filename)):
            from gensim.models.doc2vec import LabeledSentence
            tagged_sentence = json.loads(line)
            tagged_words = tagged_sentence["sentencePart"].split()
            tag = tagged_sentence["label"]
            yield TaggedDocument(words=tagged_words, labels=[tag])

training_file = open("train.json")

labeled_line_sentence = LabeledLineSentence(training_file)

for line in training_file:
    tagged_sentence = json.loads(line)
    print tagged_sentence["label"]
    print tagged_sentence["sentencePart"]

model_dir ="awesome-model.cs"
print "Loading model ..",
model = Doc2Vec.load_word2vec_format("models/" + model_dir + "/data/part-00000", binary=False)
print "done."

print "Training .."
for epoch in range(10):
    model.train(labeled_line_sentence)

print "done."

print "All done."
```

**Comment by silentsnooc** [comment]
Is there a chance that `Doc2Vec#load_word2vec_format` should have assigned that at some point when it loads the word2vec model?

**Comment by gojomo** [comment]
The word2vec.c format is just vectors – not all the state required for continued training. So `load_word2vec_format()` does not create (nor intend to create) a model on which training can continue – its return value should be considered 'read-only'. (And this is especially the case for Doc2Vec, which needs a bunch of other structures initialized based on the intended corpus.)

You could look into `intersect_word2vec_format()`. For a model that's already been initialized with a vocabulary and related structures (via `build_vocab()`), it will scan a word2vec.c file and for any words that overlap with the current model, use the vector from the file, locked to its current value. You can search the discussion forum for [intersect_word2vec_format] for more about its potential use. 

Any such use is essentially experimental/improvised – ParagraphVectors/Doc2Vec does not need word vectors as an input. I've not seen any published results documenting benefits from trying to seed the Doc2Vec process with word-vectors from elsewhere.

**Comment by silentsnooc** [comment]
Hi! Thank you for your fast response! I will take a look at that.

Regarding the use of already trained word vectors: What if I want to use a pre-trained w2v model? Why would I want to learn a complete dictionary and then learn the paragraph vectors with it? Aren't the word vectors and the document vectors two different sets here? After all I might want to test out different word vector models with doc2vec but not having to learn the complete dictionary again and again. Am I getting something wrong here?

**Comment by gojomo** [comment]
What benefit would you expect from using a pre-trained w2v model? 

Word vectors are not a required input to the PV-Doc2Vec process: it requires *text*, not *text and candidate word-vectors*. The fastest-to-train (and sometimes top-performing) Doc2Vec training mode, DBOW (`dm=0`), doesn't involve Word2Vec-style word-vectors at all, unless you turn on extra Word2Vec training with a non-standard option (`dbow_words=1`). 

The pre-scan which discovers word-frequencies and doctag-frequencies in the upcoming training corpus  is a small part of the overall training time – one pass compared to the 10-20 (or more) iterations common for Doc2Vec training. And even if a word-vectors file (of the word2vec.c-export format) had word frequencies in it (which it doesn't), you'd still need to do such a scan to size the doc-vectors structures for the expected number of unique doctags.

**Comment by silentsnooc** [comment]
Okay, maybe I got that wrong but I was under the impression that doc2vec requires trained word vectors. What I was planning to do is trying to classify unlabeled sentences and test if different pre-trained word vectors perform differently well. E.g. using the pre-trained Google word vectors compared to a domain specific set of word vectors. I was under the impression hat I learn a vector for each label where this label is derived from the context of the present words e.g.

```json
{label:"house", sentence:"This house is nice"}
{label:"car", sentence:"This car is slow"}
```

and of course, if I have already trained a word vector model, why would I want to learn the words again from a smaller and potentially slightly modified data set?

**Comment by gojomo** [comment]
You're mistaken; doc2vec as described in the 'Paragraph Vectors' paper and implemented in gensim doesn't require word-vectors as an input. 

You could imagine shoving some word-vectors in as a novel experiment. (This wouldn't have any effect in pure DBOW, which neither needs nor bootstraps any word2vec-like vectors per input word.) There are lots of such variants you could try: are the word-vectors locked against further changes or continue to update based on the new texts? If they update, at what rate compared to all-new words found in the current texts? Doing enough Doc2Vec training for the model to 'converge' on the doc-vector training might effectively dilute all influence of the original word-vectors with the new training data, making the exercise of initializing the model with other vectors superfluous. But whether any of these custom variant approaches improve over vanilla Doc2Vec would be unclear until you run the experiments. If you do, and can write up your results, please do!

(Same goes for your Spark hypothetical. You'd have to be specific about what kind of not-vanilla-Paragraph-Vectors you're doing, and then run the experiment, to know if it would help.)

**Comment by silentsnooc** [comment]
Hi! Sorry for the late reply but I didn't have time to investigate further.

So.. The thing is that if I use pre-trained word vectors e.g. by intersecting the set of pre-trained words with the vocabulary given in the corpus then I'd expect much better document vectors than if I just use the randomly initialized vectors from Doc2Vec.

I can actually test that and write down the results if you like.
