### ISSUE TITLE
Tutorial fixes 

### ISSUE THREAD

**Issue by jonasrla** [piskvorky/gensim#682]
On line input 13 of [Notebook 1](http://radimrehurek.com/topic_modeling_tutorial/1%20-%20Streamed%20Corpora.html)
there's this function

```
def split_words(self, text, stopwords=STOPWORDS):
    """
    Break text into a list of single words. Ignore any token that falls into
    the `stopwords` set.

    """
    return [word
            for word in gensim.utils.tokenize(text, lower=True)
            if word not in STOPWORDS and len(word) > 3]
```

And looking closely, stopwords is not used at all, instead it uses STOPWORDS.

Also, the corpora of the [Notebook 2](http://radimrehurek.com/topic_modeling_tutorial/2%20-%20Topic%20Modeling.html)
that is, this one simplewiki-20140623-pages-articles.xml.bz2, is no longer available, because it is too outdated
That can be fixed simply by referencing the lastest, [simplewiki-latest-pages-articles.xml.bz2](https://dumps.wikimedia.org/simplewiki/latest/simplewiki-latest-pages-articles.xml.bz2), that can be found here
[https://dumps.wikimedia.org/simplewiki/latest/](https://dumps.wikimedia.org/simplewiki/latest/)

**Comment by piskvorky** [comment]
Yeah, sounds good. Can you submit a PR?

**Comment by bhargavvader** [comment]
@piskvorky , I can't seem to find this in the code base of gensim... The only tutorials I can find are the four in `docs/notebooks`. Where are these notebooks found?

**Comment by piskvorky** [comment]
Hmm, good question. I think @jonasrla is actually talking about this repo: https://github.com/piskvorky/topic_modeling_tutorial, and just opened this issue in the wrong github repository.

**Comment by jonasrla** [comment]
Sorry, which repository should it be posted?

**Comment by jonasrla** [comment]
Sorry

**Comment by piskvorky** [comment]
Continued in https://github.com/piskvorky/topic_modeling_tutorial/issues/6.
