### ISSUE TITLE
word-topic assignment at the document level

### ISSUE THREAD

**Issue by aaajjj333** [piskvorky/gensim#688]
Can you add a function to produce the word-topic assignment at the document level similar to the mallat tool?

The file produced by Mallat looks like this

> #doc source pos typeindex type topic
> 0 c:\File1.txt 0 0 text 3
> 0 c:\File1.txt 1 1 project 3
> 0 c:\File1.txt 2 2 corpus 3
> ...

Thanks,

**Comment by piskvorky** [comment]
Closing as duplicate of #683.
