### ISSUE TITLE
make normalization a transformation

### ISSUE THREAD

**Issue by piskvorky** [piskvorky/gensim#69]
Right now the similarity computations assume *cosine similarity* and transform all vectors to unit length implicitly, inside the `*Similarity` classes.

Instead, make normalization an explicit transformation and leave it up to the user to choose which (or whether) normalization to use. Example  `vector = norm_l2[lsi_model[norm_l2[tfidf_model[bow_vector]]]]`.

The most common cases (L2 norm, L1 norm, identity) should be pre-defined, probably in `gensim.matutils`.
 
Also connected is issue #64 (allow custom similarity metrics).

**Comment by dsquareindia** [comment]
@piskvorky can I take this up? Should I add another parameter to the Similarity constructor to include a `norm` parameter with default as `norm_l2` and other o? As you suggested, I'll implement l2, l1 and identity in matutils.

**Comment by dsquareindia** [comment]
can this be closed?

**Comment by piskvorky** [comment]
Thanks a lot @dsquareindia !

Successfully closing a ticket from 2011, that's really rare :D Great job.
