### ISSUE TITLE
Size mismatch between document corpus and document vector

### ISSUE THREAD

**Issue by satarupaguha11** [piskvorky/gensim#690]
I have a 90594 documents that I have for training doc2vec with 100 dimensions.. when I check the size of syn0 after training, it is (32592,100). The size of vocab is also 32592. I don't understand what is going on..

**Comment by tmylk** [comment]
Hi,

vocab contains all distinct words in your corpus. It is different from number of documents in a corpus.

**Comment by gojomo** [comment]
Also note that the doc-vectors (vectors learned for each unique doctag seen during training) are inside `model.docvecs.doctag_syn0`. If you've given each of your documents a single unique doctag, its size will be (90594,100).

**Comment by satarupaguha11** [comment]
Thank you so much for making this clear.
